apiVersion: v1
kind: Secret
metadata:
    name: aws-cloudwatch-creds
    namespace: cloudwatch-to-loki
type: Opaque
stringData:
    #ENC[AES256_GCM,data:0ZVQ6NUm49vl6EIz6GVRR3zV/GX7KNtHHqN5Wu2su1O1h4FtzO592TTBE5WhJtEiFUtPDsANdJXF41wgh/9U,iv:W/6ZcOpNcDpsn4tT97+3vT+uxhgAlblSfHDhoZHNSRA=,tag:BlfUWAFmVaKPc8LK310OYQ==,type:comment]
    #ENC[AES256_GCM,data:YvxStn6w0M+kBxGzB3Z3djKauRR0/7Rz6xzAuxHL2GkopSNPrCgeI5tpEeNdpVKSjSm5tVu/nxtswIP/Q4o=,iv:WWflKZOjSHB6HrRjsqvCqzViJkRqu29usD6WU7bsblk=,tag:mhDbD3SxfAhY1ZABS8rtPg==,type:comment]
    #ENC[AES256_GCM,data:FfVnTA/mJ0dKT50aLG67aDXzO/MCdk9I08O8BjJie3L/ov5UVkjj21gvCmd2sQ3eGv61AHqqv+wyQw==,iv:Q4OM+B3lKv+2ZbSTbOdQiRzzbTY2GWw83SOAMKc8keE=,tag:MM27N8o2+D2Ff5sCvsO2+A==,type:comment]
    #ENC[AES256_GCM,data:JGKxJBk058qdkpMBpmmQxDQ6enKPFrFHoVszkA==,iv:ba8GmnyS1yKt7/drgp5gCpZuY2pYoFXHO2OsXhc39X4=,tag:mB94ACkOijDNvRGrEl5QVw==,type:comment]
    #ENC[AES256_GCM,data:FNOlBaVlcB2f7xZr7pdFmzau92eyv4V9GIMUyLGQskG3frgIM3b99azAsnvUrFhTs48W/ZziIqGynHuh,iv:NLpRlR/atFIaMznMmYPnZEAicU3ypZDGoeLRgCIrVUs=,tag:ua7LRR5HA3yhZVxCQZv2bQ==,type:comment]
    #ENC[AES256_GCM,data:qsnKZ314ojlD0VlkpR378mdlJgYK5payE8OdyZ98PF5GWguFEWnMyLFnLfc=,iv:Oe5DT4shVWFyZ0gg5EX/RXffLOvXAKQg5AH9mxT2K5w=,tag:Uq6xpVMGtmBihT/Xak9GXA==,type:comment]
    #ENC[AES256_GCM,data:dsiGWzgRmVRT6qFlJhPDfz+QsPG+1tpM7X8s2hoCF9z1BbNV,iv:XpeTDw7aX0kQUNW1Y8J9ddTZfYm4LMbhhp+focsH5RY=,tag:E14b5CAFZDWnyn9MXSw1rQ==,type:comment]
    aws_access_key_id: ENC[AES256_GCM,data:pmllvJIOn2UjHKPflg6Ka6/37UQ=,iv:225lD3s/Eef3UrtqOVeLMrsusRqFhQdWmQ6e7qj2ess=,tag:XuJg4IarDruxZ7+7CM0ahg==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:VPNEfLtAB6K2KEaStYkMX439cJZZ99RGeluygHhxRH5I8QnnoFyWAw==,iv:WzwCgTxOPxTXBiifrpmiMwFEr3JRPT26FiR8SbpZdwg=,tag:GmZVi1rgLMw2mcvaOn3PWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1L3BFTkZBSWxxdU1MUGtx
            RS9sZG5JbXhHcmR1RjBFOUwxM2cycXdrTm44ClhhK093S25BQUhHeElZZTJCWk5O
            clhmcFRsQ2dVU1RjVlJmM04raXprdGsKLS0tIFRjak5vc0xqa1RCRktQQWt3bTZw
            TDhuemwzd2g1dDZ3Mm0zM0s5ckd6MmsKHXoPMwQ3seXW9hMTGnk6x/7h1tZ8wYTL
            3WtvSPcBUJ9KA+K/uM3+D9YuXzGB6lO0ro3VIahpdr6owJeH+q1LaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VTNzWVB0NUR6VWdZNzVB
            V0tycCsyK1gxZzVZdlZzRFNDNXFUN3FoV0hVCk50ZHZ5N3o2M2ZvWnV4QldDUURl
            Y3dTOXZTaGdNMEc1U1F3WG5IRWdPWFUKLS0tIGl2Q3Z2SVlxUHljRzhrNGlOdlQ2
            UVR4UzlDdGUwRTRGdHlEdTlEc2wwL0kK+GWly/3i3wLdF+J34oylV/zThu73VpJC
            VsokxFstohJkUfOoRkQezIdB/E33WJLFG2lFl1mOmShMhm6k792MTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T03:39:23Z"
    mac: ENC[AES256_GCM,data:CCwYlA0HPc+DGcOjf12MBa4V9Nm1woPDAyhAzJXvdLi/vbPyaNNm21SKakBpVkRg4c2eVjyVlWjyd0gcr0klEa+aXxBx+Rc0Dgozh7cHE337gjXmRof/M/BlQxvqBW8gVVWlILS1U8SMhgE4jPz6d8NoikbyPLAjVa5+JMbKizU=,iv:GLOZhZ68QRjHiohOcrl1R/cBbsciWfxkpAGB+6M6PYM=,tag:uX5Bpv4AqMcVHwGgSZegPQ==,type:str]
    version: 3.13.0
