configuration:
  backupStorageLocation:
    - bucket: velero.wind.etherport.net
      provider: aws
      default: true
      config:
        region: us-west-2
  volumeSnapshotLocation:
    - provider: aws
      config:
        region: us-west-2
  features: EnableCSI

credentials:
  existingSecret: cloud-credentials

initContainers:
  - name: velero-plugin-for-aws
    # renovate: datasource=docker depName=velero/velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.13.1
    volumeMounts:
      - mountPath: /target
        name: plugins

snapshotsEnabled: true
deployNodeAgent: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: false

kubectl:
  image:
    # renovate: datasource=docker depName=bitnami/kubectl
    tag: "1.33"
