apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: critical-apps-daily
  namespace: velero
spec:
  schedule: "0 1 * * *"   # M145: heavy/light interleave, 30-min spacing (light)
  template:
    includedNamespaces:
      - home-automation
      - plex
    defaultVolumesToFsBackup: true
    ttl: 720h0m0s
