apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: kube-system-daily
  namespace: velero
spec:
  schedule: "0 3 * * *"
  template:
    includedNamespaces:
      - kube-system
    defaultVolumesToFsBackup: true
    ttl: 720h0m0s
