apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero

resources:
  - critical-apps-daily.yaml
  - cue-daily.yaml
  - infrastructure-daily.yaml
  - kube-system-daily.yaml
  - monitoring-daily.yaml
  - ollama-daily.yaml
  - plex-daily.yaml
  - postgres-daily.yaml
  - technitium-daily.yaml
  - traefik-daily.yaml
  - wikijs-daily.yaml
