apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: postgres-daily
  namespace: velero
spec:
  schedule: "0 2 * * *"
  template:
    includedNamespaces:
    - postgres
    defaultVolumesToFsBackup: true
    ttl: 720h0m0s
