apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: wikijs-daily
  namespace: velero
spec:
  schedule: "0 3 * * *"
  template:
    includedNamespaces:
    - wikijs
    defaultVolumesToFsBackup: true
    ttl: 720h0m0s
