# SES Identities for homelab email
#
# Domain identities:
# - etherport.net - Primary homelab domain
# - grahamsmith.net - Personal domain
#
# Email identities:
# - g@grahamsmith.net - Primary personal email
# - grahamsm@gmail.com - Gmail backup
# - graham.m.smith@me.com - iCloud email
#
# NOT managed (out of scope):
# - stopthecastle.com - personal/forwarding domain (in cloudflare-personal)
# - smithforsb.com   - personal/forwarding domain (in cloudflare-personal)

#------------------------------------------------------------------------------
# Domain Identities
#------------------------------------------------------------------------------

resource "aws_ses_domain_identity" "etherport" {
  domain = "etherport.net"
}

resource "aws_ses_domain_dkim" "etherport" {
  domain = aws_ses_domain_identity.etherport.domain
}

resource "aws_ses_domain_identity" "grahamsmith" {
  domain = "grahamsmith.net"
}

resource "aws_ses_domain_dkim" "grahamsmith" {
  domain = aws_ses_domain_identity.grahamsmith.domain
}

#------------------------------------------------------------------------------
# Email Identities
#------------------------------------------------------------------------------

resource "aws_ses_email_identity" "g_grahamsmith" {
  email = "g@grahamsmith.net"
}

resource "aws_ses_email_identity" "grahamsm_gmail" {
  email = "grahamsm@gmail.com"
}

resource "aws_ses_email_identity" "graham_icloud" {
  email = "graham.m.smith@me.com"
}

#------------------------------------------------------------------------------
# DNS Records for Verification (Reference)
#------------------------------------------------------------------------------
# Domain verification and DKIM records are managed in the route53 module.
# The DKIM tokens generated by SES are:
#
# etherport.net:
#   - dy5wbhsewzcikzt45twscs2dl4g4vma2._domainkey.etherport.net
#   - j5gqverli76qyzmlg6ulzs2ey36w6rgb._domainkey.etherport.net
#   - 5gniifohq7dsyc2lphgcnx4j3a74ofco._domainkey.etherport.net
#
# grahamsmith.net:
#   - 345d4ydpdtelkytksyw7wvzuctho5nus._domainkey.grahamsmith.net
#   - wrdadq56jdbha57jnrveghemnjco2y5b._domainkey.grahamsmith.net
#   - 637qs2t6wu5i4n5na7dnsf5j5p2ufhao._domainkey.grahamsmith.net
