apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backups

resources:
  - ../../base

namePrefix: s3-sync-media-

patches:
  - target:
      group: batch
      version: v1
      kind: CronJob
      name: s3-sync-template
      namespace: backups
    path: patch.yaml

configMapGenerator:
  - name: aws-s3-sync-excludes-share
    files:
      - excludes-share.txt

generatorOptions:
  disableNameSuffixHash: true