apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: open-webui
  namespace: ollama
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`chat.wind.etherport.net`)
      kind: Rule
      services:
        - name: open-webui
          port: 8080
  tls: {}
