# SOPS-encrypted secret for Wiki.js database credentials
# Encrypt with: sops -e -i 02-db-secret.sops.yaml
# Password MUST match postgres-app-credentials in cnpg namespace
apiVersion: v1
kind: Secret
metadata:
    name: wiki-js-db-credentials
    namespace: wikijs
type: Opaque
stringData:
    DB_PASS: ENC[AES256_GCM,data:KpdpA8e+2bHeHbhd5cYuQ/dZVevkaYsTpVbDfTIyARs=,iv:rocr6+ubh1u2emjXdIE8LmB4KajtMh1kJ4LH8ZLufL4=,tag:dp7ymSm6yXIJihav8tHhhA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjei9iVWswMFg0bGIranBP
            ZWhySEJzZkJEbGtMQWQ3UUpqM2tlMVQvZ1dzCkU0WXY5MmlaaVhSSzNMUnVqWW05
            anBnZlRpVEdmenlMaDFLOG1kR0tHUzQKLS0tIFp0VlhKYTBoNGtTL3Brd0pWeW10
            VjF6VGlZc1czU0tmdk16OEJLVmZPcmcK+Rb9Qb0r0JUuMY1dX+4/9sW1eBrlzonx
            jBY3S5kPaZAlSazMN1FhIp+5ELlTc9Y4eGU9zgbX3BZkS5ofoDVMSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaOHpFSldmaXMyTEtkQ0Rn
            WCtFNFZ2ZklZK21hNmk5Zk9QdEpPbkNUQWtNCjc3OWZVR3hqc25Mdm5FTU1PMDhV
            RGNCWFZDYjgrK1ZmeUtIQ2J0TDE0eHMKLS0tIEt6WmI1VmxtVWFjVFRqTldPSnRL
            WUswM2RtdDVMWVVaUTFKYmlJbnBBZEkKLW3JBW50xPgWQtkJCScd8u3i+typP78A
            XKQCH/0QQrxSYDetrzFJeV14tFUi2/4I58TRh7KMEsVCs3CUR8Wdyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-05T16:23:26Z"
    mac: ENC[AES256_GCM,data:5RKCpLP9sTLU21CYf2H/kSSk0IYX922rDEwGBm5is5ne/Ggt2VFEGfZ7/P7J+XN9GWUB3r0KryWhbUAWTcvEEdlXmaSmcg8xjXN1zy/4tO+5cLNDbELwnxHJHw2KbO2n18RrTjHvSrLcY0frWdyXRp681WZlpIasbLEGvZJ3NhU=,iv:gZPGDGZ1kNVRq7CKzivk6p/n7bxnChEstxM1AXDiXCs=,tag:8WrKVybSJ2HFhvVaA5tfLQ==,type:str]
    version: 3.11.0
