# SOPS-encrypted secret for Wiki.js database credentials
# Encrypt with: sops -e -i 02-db-secret.sops.yaml
# Password MUST match postgres-app-credentials in cnpg namespace
apiVersion: v1
kind: Secret
metadata:
    name: wiki-js-db-credentials
    namespace: wikijs
type: Opaque
stringData:
    DB_PASS: ENC[AES256_GCM,data:KpdpA8e+2bHeHbhd5cYuQ/dZVevkaYsTpVbDfTIyARs=,iv:rocr6+ubh1u2emjXdIE8LmB4KajtMh1kJ4LH8ZLufL4=,tag:dp7ymSm6yXIJihav8tHhhA==,type:str]
sops:
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcDMxL1FkUWJjaVh2clpS
            RnA4VGI1eTYvYnhHb0RubW1ySWU4WDdyblNJCmdSZW1TNnh2aVQ1d1lUL1J1T1Fs
            K1l6SUFMN1NBSElJVGkzUGRNV1gwWk0KLS0tIDgrcU81bDVVTTJreGVLQVB5MDVh
            Tm9hQnU0SzZ4NlErcnFBQXdqSFF1ZjAK1gj7ABDwgkuDIawvaYos591Yh8XiacLf
            9X9R/NE8tXYoPzGWW/3yt598Ow5vAyCmX17fONDq6k8WBubGMuYImQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-05T16:23:26Z"
    mac: ENC[AES256_GCM,data:5RKCpLP9sTLU21CYf2H/kSSk0IYX922rDEwGBm5is5ne/Ggt2VFEGfZ7/P7J+XN9GWUB3r0KryWhbUAWTcvEEdlXmaSmcg8xjXN1zy/4tO+5cLNDbELwnxHJHw2KbO2n18RrTjHvSrLcY0frWdyXRp681WZlpIasbLEGvZJ3NhU=,iv:gZPGDGZ1kNVRq7CKzivk6p/n7bxnChEstxM1AXDiXCs=,tag:8WrKVybSJ2HFhvVaA5tfLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
