apiVersion: v1
kind: Secret
metadata:
    name: cue-app
    namespace: cue
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:rX9Qou7KsOosq69/J3ImvtlVaAFqWM8mktDuAqucgk3HD2OZ0c3SJUgXYwbLZdFx5GNyAVrqhuJXLdAQdmAcNmXRPQmo0GlUJP6fkm2J+WwRoMYA7NPLramDDAlTTDFK02DXaLlR8JK7E/K4,iv:GyqX5LrAc0IFqMiWuZxkwWu+aqznASqz52Aela03aZs=,tag:JN9ksCyMXndw/oe+/Lu2rw==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:iPj5plgoFLIHxULfHvVSLNJwhzW2TQ3IxSbE99KiRZTOv7k6wPKKY8YWC/mdRQ==,iv:KCLrqfHwz7X2cICWjEYcMr3qCYhecQUdOaE21MAxPQA=,tag:xm4qQKAmJ3Yx62KFHeBQEg==,type:str]
    TELEGRAM_WEBHOOK_SECRET: ENC[AES256_GCM,data:EgZWVc7+pYZtO43FTDUSLy1zWppPBUUWKAzXNLDRBXcjj10i0xr2ufEAME5IFosGZg2qFBFBYAX2hXxEPjZdxw==,iv:hRYwoXby/Msw20LhNQnOkOwH+yiTXpQhHbnsPBUxwsw=,tag:IQmcdK6b4xIKWneGMb8fiQ==,type:str]
    TELEGRAM_ALLOWED_CHAT_IDS: ENC[AES256_GCM,data:eeMFPojzUrOPrQ==,iv:wF4zbqE15v5AMrvB1TeMP4zvSpKXGVUxjHczZlm2PTI=,tag:lOy6RR6umo7r3Utd8vlSng==,type:str]
    TELEGRAM_USER_ID: ENC[AES256_GCM,data:Bk4f43UU2YynAwkYXOOGV4b6IMDy4eGJzTHi0sa6wVJ5sCu7,iv:VcQ0dwdxOgcSqBf1+lagsP1gCpb96G/gYhWM/ITYvIc=,tag:6QpiIhIIqB5mEMNsJQpJ3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYUYvMVB3WEpXd0RmU0hF
            ZUJqK2gxT0ZicVF1YktRL0p4TG8zcSs3eWxzCjdXL2ZLSlFiYTNQMnFtcGFXODVN
            a2NvRFpRUGViSkU0OEdEczY4alFFT0kKLS0tIC84cDRGd21HaEhDQzFERE5XdzJV
            SzQyV0hDdDlaWmtlWC83UEhqQ2o0K0UKo1nG95kzxEb2VzKrlDXd447nlX/FsjHH
            ZageGrgttm+7Tbvza8delul8a1/++wueR3cjzsdrCo2NtKaPLl7jLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T00:35:59Z"
    mac: ENC[AES256_GCM,data:i63mv+R5WQps2/zkrmJF1rLigj8TvNVQsSWHIJEe0xsmqqXXluQfaovCIuEcQ11A4TnZQvdfnpHnbk/7aRKOA5M7+rQTLWblfR7wq9OErC6S6H3i5WiZNyTO1mK1A4miladWiLdJeMkGlJTdbafSnobF/pmKxwi+t5ua8tVO9sw=,iv:u9iMAbb2OpeEZ6DoiOu0bsJzthAU8L7zk/InVudECvM=,tag:56QMAN40f2WAac2q6lHtBw==,type:str]
    version: 3.13.0
