apiVersion: v1
kind: Secret
metadata:
    name: cue-app
    namespace: cue
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:rX9Qou7KsOosq69/J3ImvtlVaAFqWM8mktDuAqucgk3HD2OZ0c3SJUgXYwbLZdFx5GNyAVrqhuJXLdAQdmAcNmXRPQmo0GlUJP6fkm2J+WwRoMYA7NPLramDDAlTTDFK02DXaLlR8JK7E/K4,iv:GyqX5LrAc0IFqMiWuZxkwWu+aqznASqz52Aela03aZs=,tag:JN9ksCyMXndw/oe+/Lu2rw==,type:str]
    CUE_WEB_TOKEN_SECRET: ENC[AES256_GCM,data:wr5LcyDHt3SC/8mSFaXOhn+QDvZcvZFfiKAMVFcHZrRfGcB2oMqWz5BFidinVSRMvY0JhPUwpjzwABmY1MGWDA==,iv:guDFzh6XkvYeuQQzAoGGeHjGBJgvqUN+J9MVC1TpMvM=,tag:bPelUdL9GzAWN+xf6D5lvQ==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:+rWoVsfs6FyXxfNuq3IfqIiGPEaOh7MFz7UkLNcgmMBCEjM2ylmE01pqvQbYqAguB39neg2RLs4AzDyjGYOVqwoklK86r3TN/539bpoeH9KgZO7NalWk,iv:PSGHtYY5i+0JNvM8yU6uefHrfkG/bDH7ExlgroL3zcc=,tag:LOGPlgVIysCfU66/1PdyBQ==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:SPeXyoXMrim4Z4EIVjHB9+qJ7PUU0o4eZnvwwyWxcWjap80FpQ799yA0zA==,iv:/HCLuwFN/zeUMAkZiusjyjgHz2eMcxAPn495yOIMxCM=,tag:8G2OVCuwzGsEuXOUxPGFKg==,type:str]
    VAPID_SUBJECT: ENC[AES256_GCM,data:7qVvogL+wfRi4kcWs8PnlNbCnZys2SSeGw==,iv:EwWLwyrzyCeAumae33193G07rjn4Yl7EK/PqPvx3kio=,tag:n2eIlxuA9k1MDhowXeja8Q==,type:str]
    CUE_HEALTHKIT_CF_CLIENT_ID: ENC[AES256_GCM,data:aI7vPgth5cpkzIkqah0ZbamJV/OYXiirptDZROw4y9V7CIjQuN8i,iv:EeDhXHAsShoFriEKU3dIRYzeB2fxXiFlzRM9h4aSRdQ=,tag:TBI3/ipLjvY8VUQ2DkhI4Q==,type:str]
    CUE_HEALTHKIT_CF_CLIENT_SECRET: ENC[AES256_GCM,data:jOl4KueA54+WjmMWW2gBmnbFG+gMHUH25xc9p9FbpgBv0o0trqtPuJ3Kqcoy/h+KpXNNp1+E1JQHKM09QQ4reQ==,iv:58VsfNbyn37wKHBV5Q3WvownHWU1N3O2dIaC28PkedQ=,tag:1qbeR0DK0W+8Z+HPLJ63og==,type:str]
    CUE_GITHUB_TOKEN: ENC[AES256_GCM,data:OeDloNBUUTafLR7mYa5vQIv55QcGEgnsXl1bD2d/VEU37DvKFfAe7ifH2wgGto3qfTZteXknT9djhGcZoIHMjzeT3TUt6WBKygSTm69OKDZvqG88CTIN0Ja1JWpi,iv:n7rE8lFo5VRzhyrLm6b3KLXH+dSeA68sAHG7yyUCih8=,tag:8Uq339ztpUjl5xH3Gt37qw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUGxLTnF6czltcEIwcC9v
            WHJZM1ByMmxhYXdqdzk1dGFxZk82UFhqaXc4CkhyYTRmblAxenFZc1pCRnB4VHdP
            OFFXVW12YzRsd2lKdzNiYzBBaDVRSkkKLS0tIGZlTFRzUUozNHk3Y3ZJbHNOdkRU
            SE4yL1BnSmZzdEJrUDBVb1AzQjQ4d1EKOYuzlz6t9k6+7Km3qsey0t3o1gOKnaM4
            r8QaSAcOSuNYcoJV3gnwnUjV2ROp5foa2pkHojKADVhZp/GK7E74jQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdXIwaU1oQ3RPR0tmcDRO
            OHRPSFdpd3puSGZtdVpRczcyNmIrNTZDMWtvCjlMcU1RblFFUjF6WjNQTmZZNW5v
            VWQ4Ly9tRG9YOWNLVllLd0U2cSt3WjAKLS0tIFBpTzNqYjg5ZVdqb0ZQZ2pXYTBB
            dHJEeVpMWmpldlYyN3FRVTNkNGtlZkUKnJwfzK4VwRZ05/6eTJhQA/T5ZJUGugi+
            EHV42sJvWdNfdmn49M5wiPYzRwEUZ58zTP4yPpOVYdr/2FCg7a+WoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T21:32:14Z"
    mac: ENC[AES256_GCM,data:jxvh/9eERQPhhxyzlOontIEPmLDtKs3GUP3g12k9Jm4qjwjoP8FiHkJl+crxNRAFTk0f8EeFsvMxhPvlLHtzXfUYFS6KTQ5nToE1KBcDSudgqgB8WS1XR04PKfQZ5agaaXzaoKxo/4N5H2M0rJjyIpOwqSWn3bwPob2siqj2DS4=,iv:Gsdea5yiGRqKX+4KahRNpeVDBRlWhc+A0DDuvIHSpWY=,tag:lm/JBphUHwtyGgj/4leBbg==,type:str]
    version: 3.13.0
