apiVersion: v1
kind: Secret
metadata:
    name: cue-app
    namespace: cue
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:rX9Qou7KsOosq69/J3ImvtlVaAFqWM8mktDuAqucgk3HD2OZ0c3SJUgXYwbLZdFx5GNyAVrqhuJXLdAQdmAcNmXRPQmo0GlUJP6fkm2J+WwRoMYA7NPLramDDAlTTDFK02DXaLlR8JK7E/K4,iv:GyqX5LrAc0IFqMiWuZxkwWu+aqznASqz52Aela03aZs=,tag:JN9ksCyMXndw/oe+/Lu2rw==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:iPj5plgoFLIHxULfHvVSLNJwhzW2TQ3IxSbE99KiRZTOv7k6wPKKY8YWC/mdRQ==,iv:KCLrqfHwz7X2cICWjEYcMr3qCYhecQUdOaE21MAxPQA=,tag:xm4qQKAmJ3Yx62KFHeBQEg==,type:str]
    TELEGRAM_WEBHOOK_SECRET: ENC[AES256_GCM,data:EgZWVc7+pYZtO43FTDUSLy1zWppPBUUWKAzXNLDRBXcjj10i0xr2ufEAME5IFosGZg2qFBFBYAX2hXxEPjZdxw==,iv:hRYwoXby/Msw20LhNQnOkOwH+yiTXpQhHbnsPBUxwsw=,tag:IQmcdK6b4xIKWneGMb8fiQ==,type:str]
    TELEGRAM_ALLOWED_CHAT_IDS: ENC[AES256_GCM,data:eeMFPojzUrOPrQ==,iv:wF4zbqE15v5AMrvB1TeMP4zvSpKXGVUxjHczZlm2PTI=,tag:lOy6RR6umo7r3Utd8vlSng==,type:str]
    TELEGRAM_USER_ID: ENC[AES256_GCM,data:Bk4f43UU2YynAwkYXOOGV4b6IMDy4eGJzTHi0sa6wVJ5sCu7,iv:VcQ0dwdxOgcSqBf1+lagsP1gCpb96G/gYhWM/ITYvIc=,tag:6QpiIhIIqB5mEMNsJQpJ3g==,type:str]
    CUE_WEB_TOKEN_SECRET: ENC[AES256_GCM,data:wr5LcyDHt3SC/8mSFaXOhn+QDvZcvZFfiKAMVFcHZrRfGcB2oMqWz5BFidinVSRMvY0JhPUwpjzwABmY1MGWDA==,iv:guDFzh6XkvYeuQQzAoGGeHjGBJgvqUN+J9MVC1TpMvM=,tag:bPelUdL9GzAWN+xf6D5lvQ==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:+rWoVsfs6FyXxfNuq3IfqIiGPEaOh7MFz7UkLNcgmMBCEjM2ylmE01pqvQbYqAguB39neg2RLs4AzDyjGYOVqwoklK86r3TN/539bpoeH9KgZO7NalWk,iv:PSGHtYY5i+0JNvM8yU6uefHrfkG/bDH7ExlgroL3zcc=,tag:LOGPlgVIysCfU66/1PdyBQ==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:SPeXyoXMrim4Z4EIVjHB9+qJ7PUU0o4eZnvwwyWxcWjap80FpQ799yA0zA==,iv:/HCLuwFN/zeUMAkZiusjyjgHz2eMcxAPn495yOIMxCM=,tag:8G2OVCuwzGsEuXOUxPGFKg==,type:str]
    VAPID_SUBJECT: ENC[AES256_GCM,data:7qVvogL+wfRi4kcWs8PnlNbCnZys2SSeGw==,iv:EwWLwyrzyCeAumae33193G07rjn4Yl7EK/PqPvx3kio=,tag:n2eIlxuA9k1MDhowXeja8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUGxLTnF6czltcEIwcC9v
            WHJZM1ByMmxhYXdqdzk1dGFxZk82UFhqaXc4CkhyYTRmblAxenFZc1pCRnB4VHdP
            OFFXVW12YzRsd2lKdzNiYzBBaDVRSkkKLS0tIGZlTFRzUUozNHk3Y3ZJbHNOdkRU
            SE4yL1BnSmZzdEJrUDBVb1AzQjQ4d1EKOYuzlz6t9k6+7Km3qsey0t3o1gOKnaM4
            r8QaSAcOSuNYcoJV3gnwnUjV2ROp5foa2pkHojKADVhZp/GK7E74jQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdXIwaU1oQ3RPR0tmcDRO
            OHRPSFdpd3puSGZtdVpRczcyNmIrNTZDMWtvCjlMcU1RblFFUjF6WjNQTmZZNW5v
            VWQ4Ly9tRG9YOWNLVllLd0U2cSt3WjAKLS0tIFBpTzNqYjg5ZVdqb0ZQZ2pXYTBB
            dHJEeVpMWmpldlYyN3FRVTNkNGtlZkUKnJwfzK4VwRZ05/6eTJhQA/T5ZJUGugi+
            EHV42sJvWdNfdmn49M5wiPYzRwEUZ58zTP4yPpOVYdr/2FCg7a+WoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T23:22:25Z"
    mac: ENC[AES256_GCM,data:w0Etv8m7W4tAXx7VQxQCvUKIcbcqDkJHN0EzDEiVoggR6raxdpZzLzIzfTdvCUVPuow/7/0MntNTPw3U0qXS9FRxSRBTE5RxOy0z2JQ6k7Yk36T61MKZIFCeYrM2VU3oLYHa1mIMGYHANsYNA1eHmhX18MY52x56yaOlXh7eV+M=,iv:oLaUIFfpgkFHfz525p45+aqGvWMaYkGLakd3ummGyOE=,tag:qFAMTS6zWhQybE6Pj4ll3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.13.0
