apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:H451PH2mSft48tYiYTVHo7PAqug6uyjQlkJdMhddHd7bnKl0TKxsc/EtUBimRPuwaKDFBAj1ckhfdFBkexICUsX9N3Qt1W1Y9Q7v3/KAqskxC5CG80k/E6tSCSrv2tLr6sPnhVEnSjGOmMJnYObIT8sl/SoayDUlvkLyoUZYwELTm6nM/SCOyRkhAVnexMybkKmRT6o29uuk2CSizImjBk4+EmkVviNLwmpqnckd8g52ROypcD7jfk3Mb2No5KbRVwPBanMtllccFycpnKpe6DgfzJjdk62e0bOTnW1rXysqreAr/mpM1cnhjSWUsOMCO2OAIcKOfUAaNdE3ff+LT2mD3dz7FGWY6wErPwwxqssUv56BaZO9u+xnTC7NY+Xa7cS7zsaxttgU1nLKcZ9ZSq65RNsUqbmm,iv:aOKfxOFxS+4z3n9i2zJkXI07W8J4zn9CrStOJoCyVTc=,tag:dc+J1+hXIAV8eSx+3AWpAw==,type:str]
kind: Secret
metadata:
    name: ghcr-cue
    namespace: cue
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVy9FMlBSS1IrZm1IK3Vq
            VytIZHoySzJIN3M1OWRmT3pmeGpuL25BNTN3CnVIWmt4Vi92MjhXdjJEMzdZZ2Ra
            WTZJQUhRRENRdlUzN0JsYW8zNnduUGcKLS0tIDdkekZqMEttSXFnN0piLzJRVzJV
            aCtjd3NseU8vZzYwbkJ6SWRXU1ZuSU0KS+fOmPuzenxwpOBtr9S9GwwPUcYzZZ3c
            KY+GTZ326ob/PrmWHdKUfC6cbdaZKblfCtwMR1jvCgEQnF++85Mnnw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMFVMcHZSRlRZOEN6S2ow
            Zm9iR2pnQ1dNRU9iUG45ZWZaRWlZNUxISjFFCkRwZnVwcXVneEtIQTBIR1AwZVRQ
            NUVKM3hkOTBtR0ZsNVA3NjNZNVBlWVUKLS0tIEdUWDUyUHlnZzZBQjZ2dXdibVpT
            bVg0ZGlLZkppWW5LVTlXZ3ZraW9EN0kKbuWVuw7/V+MVz2HZft4xGlZMlvyTAYyc
            oV/Sz0yo4Fayb/A9ZR2reORrjPgANj3rnLcArOGvXSZuLkeiRLW/1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T18:43:59Z"
    mac: ENC[AES256_GCM,data:qjUMz0YRVXJdFrqC1rbe3FvNwRZ88jLWQwLxDPnXlqy0qve5Dssn7jSFfFrqG9T00WuZTMGmUqTx5wJBCsQvH+XRnznwdefu5oSRTwpSZoRTZ0WXzvVdHgANq5QCOtRrKP5hQN5iVu6J3DcusUHqa2xrFjnvIittuMsaKJJDaGw=,iv:1aF5q4x9rA2HO/1xxKJZkSDPueygxxSrDzSTnccTPdU=,tag:NPTaZBqkh300ZRrkavUTxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
