apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:HPIvDqJt0RNZsniBlqrSYSaFACfzX5SrUUWONGS8rOpW8tNVJxMsxDbDL/MSwaoaqqQkdocY64x4rAdoNHRTxwxsob4RsdTyOchkbS+JzPW4Q/n9wPjmposjkhS940vAe0gXJRdIGaYt+RrWiXwUBO6/sxwjERP2TCkuMdd4M1TZjw2xQuHO/quvV+0/CdnKqvBzzjuoxiF8xLSLbWyywcznhnAXGeVlwZbbscgYpfVPG25yThTjSuw7gqIcmM5s+v3UA5XaMtc8v9fhKZMknj1S2jLPEiJjEOOVafHfMzdUTx8XALqHzqcGmHmbRplSdf+1hn2smqungZsxRavb85bOTa36nlv5/RQggg627mzm6g/FS/E7DhCz6nGwtCnWMGFHCrRhTVF4BWg8,iv:1xHPIf1xMN7yFbMBuh0R7JBcn1Gpk5u2lJipwKFQzy4=,tag:u4+X2bqF7u959DiP6HPXAg==,type:str]
kind: Secret
metadata:
    name: ghcr-cue
    namespace: cue
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbDRJWjFPK1locmVScGZu
            T1F0eFBXYVFmdGJIR0hsdklSb1lrOWhiMFVrCjdmL3Bsck9ZclNzSDlJUERNL1RH
            elN1YjFPSCtQZHBiWjNOS29ndXRxNVEKLS0tIE1jUGRWbldMRnRFOCtIOWc4MWEv
            VG5nOGZWUWhwRUhsSEltWWFuT1o1SHcKL9SDC/Y+DqLtXVNE9T3Y2t4s20zfMPv4
            MZNcbuHmmV89pXmhlqqgLvF5lm1TLh72TK0EVcrPxfAi//mAXJTRiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZ3BpdUZsR0g3TFJqVzky
            WWJiV09SaGJRSnVvR3hZMlcvODhESk56cW1ZClJOTjlNSjJNSWZDZWdkbEZhdHBH
            cmFISDF5TzJXNWNVRWdXem9POHdVSmcKLS0tIENDT3k2ZDFDaDZTK29lcThtdElV
            UXV4OXNPN3JuU3JXM3pEVEdYYmhYeVkKS5flEBYHo2aaquinJvl5C+TZwfrWYImr
            v+vFBSF36Ln6Wb/cb52QeSp2ziRC3uSWJhvf5uGsCNE0kcDEBVDxOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T00:35:35Z"
    mac: ENC[AES256_GCM,data:mruAXDEkqDpKGTMucNgV93zVde7P1E/JedQAy3juYnjwQPdxlzJAXoyMl7vPQOhnBsJ+URU96XHPDvib0DNZlqpI2yjgXoFnZUKjhUHWelCOJCAySs9+TKgm1lEjLH4Tk8yELd3G+hw2XnROSdAoJUfyjYsPhNjM3e3sWFlUo1w=,iv:JRZhyNvTi/e2H0hYN8ik50usne8W1gIEz0w3TYxGg2s=,tag:zSwsCSyQPdE30WrfzKGXmw==,type:str]
    version: 3.13.0
