apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:HPIvDqJt0RNZsniBlqrSYSaFACfzX5SrUUWONGS8rOpW8tNVJxMsxDbDL/MSwaoaqqQkdocY64x4rAdoNHRTxwxsob4RsdTyOchkbS+JzPW4Q/n9wPjmposjkhS940vAe0gXJRdIGaYt+RrWiXwUBO6/sxwjERP2TCkuMdd4M1TZjw2xQuHO/quvV+0/CdnKqvBzzjuoxiF8xLSLbWyywcznhnAXGeVlwZbbscgYpfVPG25yThTjSuw7gqIcmM5s+v3UA5XaMtc8v9fhKZMknj1S2jLPEiJjEOOVafHfMzdUTx8XALqHzqcGmHmbRplSdf+1hn2smqungZsxRavb85bOTa36nlv5/RQggg627mzm6g/FS/E7DhCz6nGwtCnWMGFHCrRhTVF4BWg8,iv:1xHPIf1xMN7yFbMBuh0R7JBcn1Gpk5u2lJipwKFQzy4=,tag:u4+X2bqF7u959DiP6HPXAg==,type:str]
kind: Secret
metadata:
    name: ghcr-cue
    namespace: cue
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YXBnbTlvc3ZjYm1UckFk
            Smp1SnFhM0hYZkJjSVJqa1ozQWtGQWdHQTMwCnZSeW81Tzk2TjVoWFVEL2diNjEz
            MGswZXpUMEY3ZUdoeU5tOU4yWUhjcWMKLS0tIDNUYjNxQi8xRU9PdVkxZ1pHR2JG
            UjdZRHVsdStjUE1tZkN3K1JTT2FWYlkKT7NTOXoG02ls2tr1xLS/920vyNhSMIq3
            5m6NfNv/e/SaNjAH1TbIFFW8KX5fVCzyJ5cREHh7F1CBJuTenALrsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T00:35:35Z"
    mac: ENC[AES256_GCM,data:mruAXDEkqDpKGTMucNgV93zVde7P1E/JedQAy3juYnjwQPdxlzJAXoyMl7vPQOhnBsJ+URU96XHPDvib0DNZlqpI2yjgXoFnZUKjhUHWelCOJCAySs9+TKgm1lEjLH4Tk8yELd3G+hw2XnROSdAoJUfyjYsPhNjM3e3sWFlUo1w=,iv:JRZhyNvTi/e2H0hYN8ik50usne8W1gIEz0w3TYxGg2s=,tag:zSwsCSyQPdE30WrfzKGXmw==,type:str]
    version: 3.13.0
