apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-smtp-config
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:1ANvfV6N4hB7KgmnRfesrLTJ7H91B+UeBrDsSaPXyOQcNnNceSX8Bbb5L8U=,iv:9RJsQHLr+wkHU0w28FOqQ1p6MGv3rYD6HW3VnWsqSsc=,tag:jP/AQ5pfM4eERZeQH7hFhg==,type:comment]
    #ENC[AES256_GCM,data:gtyZXl92asXggsb0ZqYc9vCFcZ8=,iv:dTqVzaURlGKDAHcCW7eL1VOSQDYae3PAGH52LfUJY+g=,tag:8KyN331++1y8toWLlQkvgw==,type:comment]
    smtp_smarthost: ENC[AES256_GCM,data:3ZgoMqvlvvhBIipyxuK6DM2mWkEMdusdJ7C6nDQuq4MM1N9XTuI=,iv:MI3v2BNH7i6yIelf5GCHLsljGk5kBwcHzF1aaN2Kqqc=,tag:O2HHGRT4HtVWTRzKoSlFig==,type:str]
    smtp_from: ENC[AES256_GCM,data:+oL+Tn8JN41ESY+qzdBofQI5+t0=,iv:j4OP+/dNFkSr4wuyF6z9A9OFOuxmrRhdqtcUWY7DYx4=,tag:yJ8HdJmPYPfb+/IgP2ECCw==,type:str]
    smtp_auth_username: ENC[AES256_GCM,data:c2pU/4xgbbKH2ziz7EgmDjBYMq0=,iv:EFFnK6YF0dgjTIOC7ViKysbznL5OIEdX2iHn8UDSPOk=,tag:3ys7K52wz7YSbpYR/AaDYQ==,type:str]
    smtp_auth_password: ENC[AES256_GCM,data:5N+qWXDjG5NsHGH2Ewy94TQpakSZ71CauUiq1HSI6eXHhUK4vOQHMfZR2bs=,iv:NAsLVhlFG3txnypylqnPl2lruE4XOV0fepJp0yECOvs=,tag:SDORpgEn8pRiHV7jiWIq1w==,type:str]
sops:
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RmVZRnNWbUZOaCsyZWRy
            Vlk4QXdpNE0rNWgwUU8vRHNySStjd2ovY1FjClpmVUxjenV3Vm5OZHV2OXVhckNw
            eVdhWko5RC80YmEzN2sySjFObDF3QkEKLS0tIHA5YTVDTmpQbWJSYVhsV0ZycDJU
            Mnp0dGcyYkxVMnl1OW5rL0lhU3Y2dGcKbkipwc5NZ2VEo2iiI7oaGVc9MTa2/sMf
            pqYCNgoxYAEtdhiN8TQRQwxcZv+XreYwLDa7yAvFZlAM2f7uHZIGfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T00:16:11Z"
    mac: ENC[AES256_GCM,data:6Lo0ZMEYnBODv4qaDcVDIFtIMfGHUxLksIVMhgpMttTD/mJ6NHxpgQUPRFsTd4q9IAbeZoHcYnBgO67C79Ii5LzJBGCfFzvPnxzJEb0ZhqBlqa8XO+NnJxTxvX74nzdOQRxfnRKNG51WgbFcjyf1BkpwpPt8MKLhCGpTcbk4vj4=,iv:tfz7mH72LEMRYeu9PrROOrTVvKC4FeAe5/G/t4RM0w4=,tag:lOrGHlKehakJrPLRQGIcgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
