apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-smtp-config
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:1ANvfV6N4hB7KgmnRfesrLTJ7H91B+UeBrDsSaPXyOQcNnNceSX8Bbb5L8U=,iv:9RJsQHLr+wkHU0w28FOqQ1p6MGv3rYD6HW3VnWsqSsc=,tag:jP/AQ5pfM4eERZeQH7hFhg==,type:comment]
    #ENC[AES256_GCM,data:gtyZXl92asXggsb0ZqYc9vCFcZ8=,iv:dTqVzaURlGKDAHcCW7eL1VOSQDYae3PAGH52LfUJY+g=,tag:8KyN331++1y8toWLlQkvgw==,type:comment]
    smtp_smarthost: ENC[AES256_GCM,data:3ZgoMqvlvvhBIipyxuK6DM2mWkEMdusdJ7C6nDQuq4MM1N9XTuI=,iv:MI3v2BNH7i6yIelf5GCHLsljGk5kBwcHzF1aaN2Kqqc=,tag:O2HHGRT4HtVWTRzKoSlFig==,type:str]
    smtp_from: ENC[AES256_GCM,data:Cz3Ise5N/5zbQ8gSN8qvbrVBOyziccVDCKkIH+R3jczZNndSAmzZ,iv:N1b4IdrbksaCnlyUYdP5ugC4foTslLIxcdMoU17fXlE=,tag:cu5VTPwZJoLUURc2Twebgw==,type:str]
    smtp_auth_username: ENC[AES256_GCM,data:c2pU/4xgbbKH2ziz7EgmDjBYMq0=,iv:EFFnK6YF0dgjTIOC7ViKysbznL5OIEdX2iHn8UDSPOk=,tag:3ys7K52wz7YSbpYR/AaDYQ==,type:str]
    smtp_auth_password: ENC[AES256_GCM,data:5N+qWXDjG5NsHGH2Ewy94TQpakSZ71CauUiq1HSI6eXHhUK4vOQHMfZR2bs=,iv:NAsLVhlFG3txnypylqnPl2lruE4XOV0fepJp0yECOvs=,tag:SDORpgEn8pRiHV7jiWIq1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkS2c1bWhYdEZRL3FkeDI5
            SlBmdFFXcHhJWlFIamZlTTJKa2FoaDZOQ1JVCmhxbXM3SGYxTC9kMkl3bWpDcEdB
            RkFmWnFSV3h1MWlKWDdhSCtuWXhoOE0KLS0tIHA2RUhPeXFWdzJDQ3hEVWg5WmdN
            WlpGQlVzSmpDSmZRUFhWWkp3RFgvbU0KTvxioiDsgLAaMw52c4J9Z3S6vI2CVpZQ
            X0NoAThZqtn8rNL/DCNGBS5wm0vqCoO7x6X/Z1QM+XIXbYG8tzGvAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWWZmbFhxSXVVK1dEd2lx
            TDBUb1dOaG5tN3NGcU82V3BXOG91a3JTMDFBCkxIS2sxb3EwaXJHRWxLZ3B1ZlJp
            azlZRi9ON0NCcVZDeU1jazh0Zml5ckEKLS0tIGJXRzY4cUVYVlE0clkwcnFqM2RJ
            M0szR09rUVYzdEhkY0l4VzMzVTYwcjAK/5HsEjzaKrPogmOeGqVJUMm64olIq/de
            +Z4Um2jSdaYd5rcQPp1T6cIGsVb2IFNfxwPIJ3MMR5qS/f0fVwObwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T17:23:33Z"
    mac: ENC[AES256_GCM,data:stxHKUmG1b/cspRvoctEXlInPO5e9+DsXQkT0CmBtwUOY3hikpze6tBHDb3pYClQW/74f/GZRKIKwpZ9UyxxBZbBli4zwKFHwC1YnjzP+db2ZQF7G4tnRyQQOM7mF4shKH9VQH05zwNFlX5yGsG9XnzBKuFCaNVNSvtPZ89bDo4=,iv:94iVF4EhUT7tQpFymTfV604Z0oNFFjh8+0Qs7mh8IZ8=,tag:xeOb/JQhcpap3sKlO9ruHA==,type:str]
    version: 3.11.0
