apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:4IhF0fA=,iv:26l6U5/ifBKIKzyCoW/u27Mc3ri8O3xtHO0zligd/UU=,tag:lJcvBRA6HK2A+17SXGBtuw==,type:str]
    admin-password: ENC[AES256_GCM,data:iTmTFpH8UGllFzpMiB2BF42h2g==,iv:hv1qll49ZIPKnIe6VsPN0FV1x/fXZvoPLTNoVKlLyic=,tag:sNeulB6qiZ1yoyT3JGZ1kA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWUpBRngwUUlONVlrZEE5
            Vi9FVVE2UVdFa3dWUklYbHowYVNJM091dTFFCmx6ZnU4cVVGWFlwN054NWZGRGJS
            RmhwSXhzajFUN285eU9abkx4SU1KSHcKLS0tIEhHT0FxbVptWmhCa2lMblZtOXdV
            aWl4azBIR1c5Y3FTaEdFMnNlZEx3L2MKLpeEv0o0J+qFOQX6mEOXyIyyHHEw4Vzx
            wXYp+vFsVWJjWpesB0OBNXCI80NyObstKggcdcdCbUQMTFYCc0aTLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2akl0NHRjZ2prMytUSWp5
            eTV4NzFCNVY1TDF4VWxYQlQyYXVMSkJJUTBrCkR6OG5XVytmeEhKbjYxWlNBdGlM
            WEFBMWdKenRidVJSQW5VclovRTAvd3cKLS0tIFdTUm5OYzhVek1xSytDVFdyaE9y
            VWs0Zm82NHpYenF1c1dKblFkeW1XM3MK+QIuU/vZuEnmDlKAOLnbBrWPGtuvSTlh
            FUB5YElA/Fa06bLyFTVUatxS30wBdwfepAr3M/8frt8jPM1aGfnAGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T03:22:39Z"
    mac: ENC[AES256_GCM,data:wcIKZlBwwaFitWL1LpYjOvc77lWT3sOI7tvWNMGslgBUZ/o2PZ7H7owkjNoSJCjaegiwYVYS/UOENWmIFIqJ6gUOB3Pndxsg20/Zzi/cHz641ToPCP40PEXjLCI30jEukqKcsZXb/aiWX0xlu5UMqVregIzXdStNsKoIK4Jv0F4=,iv:vW4ZHjz73CqmVrRsUYgoTrrv2KWoHAASz6y2yrtHx5s=,tag:KGdtDYxUhHEy2kGuviqqbA==,type:str]
    version: 3.13.0
