apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:4IhF0fA=,iv:26l6U5/ifBKIKzyCoW/u27Mc3ri8O3xtHO0zligd/UU=,tag:lJcvBRA6HK2A+17SXGBtuw==,type:str]
    admin-password: ENC[AES256_GCM,data:KxsdLwYsO5zsV1sP,iv:8gU+iJqGefEiZkXiikgS6daTLCwFuK25phhnAy+ZlAQ=,tag:iXL1KRvE0eoImmgPjYaevA==,type:str]
sops:
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSlZWTU9rdVFhMkFnZTdO
            RjdpWlREajNDRTdqdTBobDVTSFZYWVBkbmgwCks1Z1RXYTFNOUJlWExvUFV4bXYz
            Vmp3bzhyQ0lCQjJ4WU9XSlM0bjRlVUEKLS0tIEtrMlQ1Ri96WUJ4KzhseTFVR0c3
            blBVY3JocnVpazFYRGtNRHZVVStNakUKnb6TjsyuU/WDb+K3lVusTvJNLU/x3Iaw
            78diTEYWmpPzwWyvZKH0aVlXa++Xfp6f8M/rmmRRuXexNQILEExenQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T04:53:21Z"
    mac: ENC[AES256_GCM,data:cYZ39iktdGT375ZgJlYQ3PffQgDvOkCZ/SgPJrmYzspRL4XLvP+VR8HFqXqaIbCE28xzKaluSuIGXOKfZWPANuP+2JPUW7jw6ggYNaz+FF3gbypwRGKybwccvU8bksBBF8NVxwWUNQGesU5UVCjXoJFnFKr/StOz+hR+P55aBjs=,iv:0MFNyWPbXXg6k57Gasj4nDRMkMDaAiU5VbQGiNewEVk=,tag:lHSApXhjy0mujcnISe+gjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
