apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
    namespace: monitoring
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:sRv+KiPlvx7H2VRvB0MJ4t9MdNyoaCtImLtwEkeEV6JB/rR0KA+4DQQrfOL7Q5Vn1w1iURnTXO/tR79t+VJHzw==,iv:y6WTFWHUCGV0poUxTQ0MxkCeoT+6jvUORV6833tGgAg=,tag:CT7+xPpgXbo5OhOC5RffPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSVgwQ2lFbW9wbHNlL0o5
            dk9XaU4zd0Y0SEJoUk9zNUcrSUV3SEpZeUdrCnRRb2lWWWMrM0k5NmJwUHRyRGtI
            V1VUekZ2ZUlxZVR2THZaMGc0N0V6MUEKLS0tIDFuM0NFbEU3Um9mQkdrdGxra1Rp
            Ti9xSmhqYXo1dy9HRnFxRXp3Uzg2b1UKun5GPqJCjgVKwBjImt/tIR1m4DUTK2pV
            xwFzwoPWgtpDkvYn+lFx+mCEznWn+F3guWJd5sgw0xZHqZDRxNa8Fg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyREYwdTRORmJKb1ZraHFQ
            UkFremhaV0xnS1BxbUtUNWhkUkVleFprd0VrClZ4YUVScjZyYkl5a0R1VFB0dGVj
            RUxaU0ZBNUJ1SmFlNFl0QllaNzlOUUEKLS0tIE4wUzJ3TmpZdVpNcE9ncTUzS3Ry
            amRWOHNMd1d6NTQ5OUtLYVpnMFZYeEUK2PBlMVQHXbKqJU8d9N70+JLkX8dM2e9e
            Pc66iqj7++kQcYMVMyeFomY1nooImZeTwz5S6Z5ni17SzHVUhGRs4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T14:02:35Z"
    mac: ENC[AES256_GCM,data:OuqV6duuTaTQf4bYLP17eBwCibkJmbONtBTAST851v/lEajM4X/+3KU5u6ncDy9dhUFKE74G8LtHmikgcmxdqE3jh8MUtWZo8dmYfKGuoH9VFVHhhQqJx3AcLYR0peWZvK8zbd+GBrerT48X5/MH4BoIHf2O2tWtsBfgnwuX5Cw=,iv:v6s7vUYuRL69KPt47P/sjWDRCITLn3Q2LmxArj5SuhU=,tag:WK/NP0DZ2En46Wbo6Kkm2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
