apiVersion: v1
kind: Secret
metadata:
    name: route53-credentials
    namespace: traefik
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ueDPcBO8243n0lRcLwb+uZ4nRqg=,iv:XynuZcO7UgLDgbO7XB3SupNrw3eXHqoaEnGHgnxhiC4=,tag:1FqntyJKx7GEQM9g0mg42g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BbfGM3DrsL6IgkgPNy6a8WZooq+CPPWRFOVQLohXOLEZQn9DKZukVw==,iv:kbQiWp2MT1fgZ5JfP6gyW2uk5jb5SUbTKi4CkYmOW5I=,tag:W5WRqzBz0kcOH0LoB5rayQ==,type:str]
sops:
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQThqclB0TW1BRU1NcnQ5
            ZUpPL3hCa01ybGY0ZWRSaUp6ZWhVTW9KbUYwCllTZkNVUGFQSFJkQ1N1RUE3MzB2
            Um0xQ1g0OWZXejR6QXZzT1Y1bDRnTDAKLS0tIFpRUFl0T1ExUkRyVFp5UkN6by85
            aXpxMHBaWEhtVXY2L0FMVDZ2azQ2b00K8eWaOtzwx1R0o4ACoHEQBmmUdjS0VxXx
            1OmI/8Bx9+z0n7T1U2tgguBxSZBhNjWj/ohKHetR+UAMut3KKrWPtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T05:27:13Z"
    mac: ENC[AES256_GCM,data:KBxoRRf60LjN0vMO09R4WSbMiMoOAIWZenAt4DB6XcCsULTK4KQOEq/95MaSrW17VG+L6vh+IsESn8WuKn28RCFVb1Tr0CgpMka9NOqxRUnebfAF35Cn2Fwem/waqQYeFL2MsLoP1Zs3KOKNwf7Frg/fCAiVEZ7fFUBkYJ2mxcY=,iv:BeoKdEbui5qjcaYie2yy+xoHtXTuWQw9mQQBD43uHu8=,tag:bZ+rx0yUIkMmpWQv6KCzhw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
