---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  releaseName: cnpg
  interval: 1h
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.22.x"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
  targetNamespace: cnpg-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # No custom values - using defaults
