---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-operator-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: gpu-operator
      version: "v25.10.x"
      sourceRef:
        kind: HelmRepository
        name: nvidia
  targetNamespace: gpu-operator-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    operator:
      defaultRuntime: containerd
    nodeSelector:
      nvidia.com/gpu: "true"
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
    nfd:
      enabled: true
    gfd:
      enabled: true
    mig:
      strategy: none
    driver:
      enabled: true
      use_precompiled: true
    toolkit:
      enabled: true
    devicePlugin:
      enabled: true
      version: v0.17.0
      config:
        create: true
        name: time-slicing-config
        default: tesla-p40-shared
        data:
          tesla-p40-shared: |-
            version: v1
            flags:
              migStrategy: none
            sharing:
              timeSlicing:
                renameByDefault: true
                failRequestsGreaterThanOne: true
                resources:
                  - name: nvidia.com/gpu
                    replicas: 2
    dcgmExporter:
      enabled: true
      serviceMonitor:
        enabled: true
