---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "80.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  targetNamespace: monitoring
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    alertmanager:
      enabled: true
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: ceph-rbd
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 5Gi
    prometheus:
      enabled: true
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
    grafana:
      enabled: true
      adminUser: admin
      adminPassword: ChangeMe123!
      persistence:
        enabled: true
        storageClassName: ceph-rbd
        accessModes:
          - ReadWriteOnce
        size: 5Gi
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana.wind.etherport.net
        path: /
        pathType: Prefix
        annotations: {}
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          labelValue: "1"
          searchNamespace: ALL
