#ENC[AES256_GCM,data:RDeUeIW+JYBDKR0Vjz8AgRXw0hGzF4Bu9SQu96VRp7yEb9mHk8tbXmIOFAJBagG+i2VHxJgfm8QETPSfteqlqioTzw+NscxD7w==,iv:DHcDI3XRLHeID3I6LX4dKelzbs//EfWrPPCf7FA5Ato=,tag:panEPNgz01Wpjtvu4XSw9Q==,type:comment]
#ENC[AES256_GCM,data:owksjsjbNY9xupKCd6c46vHl5AUHdUHnEdDIHXqyZ4bMTA83G9dk57PH2m0pOROlvMQ=,iv:Q/lC5yConffM+42gCJFjXHhpQ8jqz2ZyMrPL787oe80=,tag:zz01BOVZZfQwEuBW5mKG6A==,type:comment]
#
#ENC[AES256_GCM,data:EDy9rOTaYztR8XX4I6k1ZVow/68F4lWMHQzykgijARua+mz5mf0d8gnD5CIH40sqCOQvq25CUHUnC1lcGLDL5aDdHmI=,iv:sYsyjVmp1npBp+vaGhgJIMGaVBEEZSAc1orsIatvgpM=,tag:3tRqJtAYP8UwKKhbDgwyaA==,type:comment]
#ENC[AES256_GCM,data:TzH1IQAYJ7ZuWEisWa7hE8YNQnUHSwyS/z+UV1nCt57nphWWkw4EI2OU2/dQasvYtD3hqZ8Ip7ZOnJVFv3k=,iv:53XJjtupZRVIa4EvceJXzr4fn6iHh2xVvg5LWWOcx1c=,tag:bY+m2BN85Fi5W8CjLe6wKw==,type:comment]
#ENC[AES256_GCM,data:jglDiVRFoK/fREmQhlwe2BEIv6rLI99UNlgtTpYxPOP6IZwFK3W7H61m7JRdtA==,iv:Z2BaHRcLAAztceCkAIUmI3ETZR+jvrt/ejkVXs/Sv+4=,tag:bwiYCwxL7vq2M2vS0u7uQg==,type:comment]
#
#ENC[AES256_GCM,data:byarfX3UBgn7lCHFlTVui9BU8zfUq/+Hk50COx5rctdw+9nfrfZzpu5F6q2K9LNYGaKoTgwvu06b86TsrmkFU8I+LroONMg=,iv:KnzO2JCBK4ukxATRVimrcL1yoZuXz7dny+HuRuelDE8=,tag:aucngC9gIdFwJwgLFNoezw==,type:comment]
#ENC[AES256_GCM,data:BmyGebougdlqyr4bcc4BnYEegUZeFyD+dvrZoUNeDkzN2MPgOhgExRG5D5DUdBRXtX299LGCRkiJUVjdqkGV3w==,iv:55zrRuQ1Ygm/r2IiFcZArOh04ueYV4C357yWK0W1sl8=,tag:rtQg4eyPGIYAqAW83czpfg==,type:comment]
ceph_k8s_key: ENC[AES256_GCM,data:zTCJXskGFA7fZ83ALBAyrTO8CA/1yBaCvdh8yNOU20yXU1HXSD2Uug==,iv:u+CylQOtBgAvCBLbPylTbjmjK0HFgudlkvozsQTD8HE=,tag:sbFRRkVR1wLzl9YujbG7GQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcmVGN1BKeDAvYW82NjdX
            ZzROOXZJVjdDeEtqZmoxcUdrcHpkaUQ5RkRnCnQxV0VMTXlMVmRJeTFjWEpLMXZC
            NmNlY3lPWklxR2JUeDZQT0JaUVVsdkEKLS0tIElsMERzYUFVNlNxM2xkazQ4OXNz
            TTFJTFZMdW53bTFvd005cHpxWkZEbTgKV+m7VSDMBxODhZnkqsNryK3VHf7Yjb6I
            QdVaabx3YSQy1ZyaOTre8Y2Zm+JoeUXV//Q9WV5k55oaLIJcY0t3sQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
    lastmodified: "2026-05-22T17:51:33Z"
    mac: ENC[AES256_GCM,data:ZkhYgKe/bkNd9P62p6cUg27N7JZKJxPGrv03L9GLWyJjP0p85Bruu6PR5J4deIjfwaleBrl9LjXTwuRM/vVJ9dH2xH3wxO9ZYb2338y6tlChnTwUkoCf7/JSvatz3AAhtAn5Gq/J0qS14LSQvsHDOzHstOLhhndfcbV7C6i/FRs=,iv:uJPTY12GeydeAfuAr1rGZlfwCEPMR/d+Cq4fqIiM6Ik=,tag:/BTW8uA0LJzGrHkQ7Bf2HQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
