---
apiVersion: v1
kind: Service
metadata:
  name: unifi-poller
  namespace: unifi-poller
  labels:
    app: unifi-poller
spec:
  type: ClusterIP
  selector:
    app: unifi-poller
  ports:
    - name: metrics
      port: 9130
      targetPort: metrics
      protocol: TCP
