# SOPS-encrypted secret for PostgreSQL credentials
# Encrypt with: sops -e -i 02-credentials.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: postgres-app-credentials
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:z5BgH+Du,iv:FBeNnEPmu3U8EtzpUXKHFXNK0zmQj0UYeEs6bG8NsbI=,tag:hLFEgs/iq8kWvSOBxxJhnA==,type:str]
    password: ENC[AES256_GCM,data:PJlUo3NswIr6BCrNmJg/2yFEwWsnv9282sqnBTvgw4k=,iv:YFinlfCLhHAVgxdVFXuCimh2AoxZCtUBLP2pYOXtCvs=,tag:Us/NIX5Zyp6eGYGIn6z+/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdVZIRzlZaTJyU29kU0ly
            ZjBxdjZFbG14ZEVMbi9VanlVMEhLa2t3clNZCjh2c1RzSlAyR1ZlaXMxLzc0S0h4
            TW0ydnVxY04yTXVLeGVaZXpUUEJEUncKLS0tIHp5bUxDZko3dzd1Q3NZWUI5V3dC
            cTFDWXBSU29nMVlsRVdrbHNiemZKLzgKbeLTONDsMTHMG4KQPOB9SG9QJzpx1cKs
            EzP1joFofK667CJnNy/8RZ+s1EcEtFdHykLeLHOIEQnLbaaEa1D0og==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVjVmUWlWajdIVTBlZmNR
            YWtKRmFDMEFSdlMrTUFRRHJpZWRmVFRXNGhjCkZpR25mZUo3ODdmMXBvVlEweHdE
            YTNBTmVjall2aUhKMzRnNkF3RlZNU3cKLS0tIEJXY1dSWE1VSWZyODdNWGY3K2hI
            Yzh2djZBNUUrTjdKclZiL2h0YlZHbDQKxqL40NBKzq/XJ6l+NfmBWzBE6q8DXQSu
            KFgdNSYAP7Fs5kUWLdl6abwcG6D9cCcN2BsBrs41ATduKq9Z7Lb9TQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-05T16:23:17Z"
    mac: ENC[AES256_GCM,data:O0UeL0kR0tjXXz1sLBP3RSatx/Y2LRDMkl5KPtZzF/iXPVvPLD6rZjNb+ChbdW51cqtcIqvnnPk7Q+1lxh7BGSvTtStNluoaQJaPnIiKiVxINZcxPcxdn/WsuAugwYaYZYjn+sssQfbUxIQAIjQzYNFBh5EQ18BzVnCQBIpNcVY=,iv:yYsdpd3dj0g7UCEHhpfRdxdVjJ+79Ouoj6CUWgU85Xc=,tag:wSqg7xqrBkbsvJadUPf48w==,type:str]
    version: 3.11.0
