apiVersion: v1
kind: Secret
metadata:
    name: barman-s3-credentials
    namespace: postgres
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:qiyaiI1gCut82AIKBxINU9GH0zw=,iv:9fOF5Kb+a0E9yjlhdbN5totIxgrW2AOdZn04pd8jZSM=,tag:YkAT0e4PPAW8CegVTlfayw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hRxwctLDDFny6j0GFav7GMe9zVWI3nF05ThnBRbIViRDj/7K1IecAw==,iv:9mBGtGMVv0E2NVuqXO+jiCylK9CXCalmBv2eP/y/wt4=,tag:fDGusd94gW6f2gw0qchXSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SFkyeUxRNzhRVHRrS1NW
            RDBkV1JjUGFEdkpYU2xpcVY4U0tuWU9oaG1VCjhleHp0dVM0cFpXK3RlRG9lUENs
            b0dXZ2wxb09IL0V3bXJPUlprQ1lnUjgKLS0tIDRKRHh1WWFhd3F0Y3ExVE1Nb1ZS
            VWx2V0RiT0JlQ1U0WUFCZzdZN0MzS3cKYQJE2Ytqm+usKsMAkykC7jHE/X569w1m
            tRL3nWBuBlvlQfO66RYpyGHnXHn7As/kxYseCf+ie3Qi9JqUaqR7Tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T18:24:09Z"
    mac: ENC[AES256_GCM,data:UxqlZRMeLhO5rLHDxziCgrhRCHuPh4dSJfOGvKLHOaQrIfvRmInd2rqhOKRPJrHzUMveKzCmhBvki91ApAAOQLRKizK1jTX4yyK/9einnZt60HIrCkDvSmqqXUzdmXQzMo7Odrxe6Lc6f17ilbXYlPpy9IkyBMSm0LUUwRCJHpw=,iv:kvkZF9YYibivXFD1Q/uhDWi6t0qGm1Nhv5Rn7Ky0nTs=,tag:XMqLtlyYk2SsH/FAtFnGUA==,type:str]
    version: 3.13.0
