apiVersion: v1
kind: Secret
metadata:
    name: barman-s3-credentials
    namespace: postgres
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:qiyaiI1gCut82AIKBxINU9GH0zw=,iv:9fOF5Kb+a0E9yjlhdbN5totIxgrW2AOdZn04pd8jZSM=,tag:YkAT0e4PPAW8CegVTlfayw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hRxwctLDDFny6j0GFav7GMe9zVWI3nF05ThnBRbIViRDj/7K1IecAw==,iv:9mBGtGMVv0E2NVuqXO+jiCylK9CXCalmBv2eP/y/wt4=,tag:fDGusd94gW6f2gw0qchXSQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbC9EYzFrelZyY3FPbEpl
            YzdJY0hHakNCWi9XQjlJT3RUTHQvREtlNUI4Cit6b0c2SGhYcHkxY2xESEJTaUJj
            cXJBT0liRnRwT2pkcm5EM2JDcWlrc0EKLS0tIHgyczBDVG55emo2c3hmU05lMlkv
            cTAyUmVjc0JtcEwrU05tUG94bG85bkUKftpCU1elBQhRZY4t3C4KXu0MBS2HGrcr
            ZflCC1pItKXboH7sLChNbSrvs4PMSwpPgMQvW3ySOy4BJldv14fXEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNncva3Q4UjI4a254TFl6
            bVRlN2EvUngyTVc3K2FwYU1GczB1eTJieUZrCk1zQ2RYV1VSdzRuT0tBUEFjajlD
            KzhhVXZyK0xVZy9rVjA0aGN5dEZaajgKLS0tIHRHYVptTHRkQVRLTVhXOS9tM1Bm
            TWF4clFzODJZZ2FMbzBWb1ZUU0hyZlkK4q6Obiwhe3DjP9D+hp/GGXPu50buqw6F
            G0Fqwrx6lio9rMVkhx/puFLrF1CwINVAdKWRIyiZan0L8jQ2M63Mdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-14T18:24:09Z"
    mac: ENC[AES256_GCM,data:UxqlZRMeLhO5rLHDxziCgrhRCHuPh4dSJfOGvKLHOaQrIfvRmInd2rqhOKRPJrHzUMveKzCmhBvki91ApAAOQLRKizK1jTX4yyK/9einnZt60HIrCkDvSmqqXUzdmXQzMo7Odrxe6Lc6f17ilbXYlPpy9IkyBMSm0LUUwRCJHpw=,iv:kvkZF9YYibivXFD1Q/uhDWi6t0qGm1Nhv5Rn7Ky0nTs=,tag:XMqLtlyYk2SsH/FAtFnGUA==,type:str]
    version: 3.13.0
