apiVersion: v1
kind: Secret
metadata:
    name: approval-hmac
    namespace: backups
type: Opaque
stringData:
    APPROVAL_HMAC_SECRET: ENC[AES256_GCM,data:41tzZ5DziUlyoQYV5yInUNGwa0GBssX8KaYCdRG28969UzrZ5eIekWXzqyTkJBmL4BckuEJ8C+iW22O3MXOdyQ==,iv:wDucUZ08znAlOYN2/kDGPfPTPb+BB8vDl3ASH0wtBgo=,tag:wpwHzkZKvD5Re6UzsqblCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYWFrbmxrZlpjL1hpTE0w
            dEFPUkJ2WmdwQU82UFg5THlMeFVIMUdpQldZCnlmOTJ6amU0aDVGbFp0QitkVlJR
            c2VNWlY1ZXQrcjZqTWMwdDI1cVhJakUKLS0tIFpQeTJ5UnJ2UnFXcUthY2Q3VEs5
            K2FrcUFkUVdWVXE5UHBRZ3o0cGRpVEEK8GZwZ+LcqaIgJkzfc+7nJGoUwPc7oaMx
            VsILyNlu3Slz+DMEu0VcrRgFcP40XNViOabaPhA+0mdQhQ+2msJR9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUGtuVWpCekhGTDV4OGli
            cjBvdDJPaDF5Q016OXF3M2hNamQ2T0RTMUZvCnZjRTBuYmx3WXBnNkMzaG9td2c2
            bE45SWttWE9EVTY1S0Y2Wlg4T0twQ1EKLS0tIHIwWlVNTHl0ZzN6bzlnaXpsOXBR
            Q1JKUVU5R1NYaU1TeGV3Kzc2VlhGcmsK13OQ4N554Vc7+zb5GBuA1dNuU8q8p5cp
            9ssbwDP8WSD+uSxZs+PhblYWTg4bEg4gMOUaPBevn38eGprMDZ/nuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T16:49:43Z"
    mac: ENC[AES256_GCM,data:y/6e9IWJB+dO8HlPdZQCCf/2QVemv4w2HSqSB4YjdMhenmRNs4dGPWxCELpuW2smTN3idWqgj3gkdIztaNkEZEGW/1b77hDUOC6QhOsNxw8IEAJn6Rkj7H82PWosSZi4VjTvelc1e4oZCgg4XYLzYUm9OHHWDOsXDTiuaoZcApI=,iv:K4vjWUT4bsBhJcHCzh/39NYuZElldMuu6o7T873lcA8=,tag:+drhhcIwywDOGtBhJ7k+Cw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
