apiVersion: v1
kind: Secret
metadata:
    name: tailscale-operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:qFg5mD8mzAqljeFFDkTnK3e3kB5rDMoWzLa0xVNE/Oi/wRefoyT/+6R//hgTZaELqtKfMHn5qX8LmK4kOAfbUFm5gQAw4Bjt2A8djsx8cffiO+plcT7VeJuYbx6iok25l42/Tjvln0kzCGu+3cydCy9sFSTm41lXxGg=,iv:KgX8pw2IF3gRYO+kz/mToSoA/Om59BjKQ8fc12RUamQ=,tag:GcHRGP0o7DzLkPo4CIIVgw==,type:str]
sops:
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQVZlNTc0cERLN1Z4cUY5
            djZwK3hCakkwM3o0aUdzQWFkUmFmMnpYakZ3CmN4WnJTakVpdkJhUHBPbzM1RXEz
            L25HaXpPYk9SYXRINGZTM2thKzdzY0kKLS0tIGxoeTltN0J4S2lwT0x3MVl0a00x
            WVNEZ2drSEQ0Y09rSE0vai80T3h5UkUKppuimsVJL2VuMtL6mk84lLw0Jfgrb43b
            rGze30smWhaY5GkOC2Qn3NhN97vDBA3Vj8Xtm+sqWkMtOzDmSe/FoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T16:32:07Z"
    mac: ENC[AES256_GCM,data:zhokfSWgh3apOCCEycOTErpln0rJ3vAsqrPlNzqrPoSafLeRP7TT5JcmrqXVLNUIun/lw64tvURHF/KVRFX3qcO3i+cOEfTlFVs0/RctNrQqpd9yaq0fdT3LXMPuuHeyOTZT5iUQTNfw7iQO7O0jJ/dg5bGne8ZXl4uFRX3mq5s=,iv:tUUOAagxbFVNgmm+JJlllPy9RFpYTkbwBbNqJb4SIWc=,tag:m3Yqzc3O+uA0fMVHYyMwgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
