#ENC[AES256_GCM,data:PCAJEAel6qqiu9GAGfu4KXHktK33a7KiIRQ=,iv:0QxPVCcXYaNozn4R4vNr0Jo4ZX6Xrq07D5PfPJY9LXA=,tag:JS6EycVXx+7bMenxrIUiNQ==,type:comment]
#ENC[AES256_GCM,data:Cmth3wLD1ZJURZf/PRdAkTM4gY91RXDnTV99IvmXVU7Rjo41dtZPVQkYskPgix8GjZOQHVE5P+svtkeF0QSqUA==,iv:Zb6xbtA40KE1pttjgz3kn8HfAIUqd1+sI8cVzcK4dCo=,tag:MQsW4FRBXP6kBYW2236hUA==,type:comment]
proxmox_token_id: ENC[AES256_GCM,data:s5UIF+2DpxV9z/1FucwfO3itUgs=,iv:Sqw9pQV5QCf/nwtfzoSFaOI+uLp3qQzwggI+BtGjGZw=,tag:TtzafPHp9cl8KVy1BoGNew==,type:str]
proxmox_token_secret: ENC[AES256_GCM,data:WzFxe8xVAvcJizZApNTjJNlIuPjg5M2p7EudNQfbrcB7ooGp,iv:FlxmNROsB/mS6/77Ij0tOCsZe7xZW4LC1mtw+tjJYhE=,tag:Rffwl2Jjgm849k3Hy2YDrg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVHAzVFBweTMyQ3J0bGZ0
            WDJNbTY3STh5MnBCSFIxWEIwRFNCbU9qdFZrCmdKdjN5N1dHUGZPeStVRnRGWXBR
            bDg5cWozRGdnN0lsazZFSE52TDFxcTQKLS0tIEdmb29CY3dUdTJQVnlWcEtGNXdH
            VlptTng0V3M2Wks1VUNFY00rSnV4T0EKn4QO5Ipdp8MJytsRXpTd2yKOl6WUdq8o
            l1AY1Se4k/mHhpl/Lpr3ExQeqw7pLYzttYKy6Imig9fEN8rR69oWlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZFEwWXEzaGVkNWZJZitZ
            byswVE1sM2dwYm5QdERERkdYYytIRyt0YW5nCnYrdHJxWm1MMWFKTDJWYmhqVGNi
            QytCTWVCRFlaK1k5WEk1MW5MbjhNZDQKLS0tIElzd0FUdkhPNDVyMUg1ZmVudHVh
            NTFISzR2Q2EwUktjMGNUWk04dUFTZjgKiO8cBD6w//uAzyaS7LohzypFWBZH9Oyl
            bKmJyadJ/KN4JL1StjGIxuLV+DaOnzk0Cf0EwiSd8VljPzBcv+GcFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    lastmodified: "2026-05-08T15:08:11Z"
    mac: ENC[AES256_GCM,data:ZWbDmDY+N2F+2HN68uUX30svtxIbyP/Krj01ScNZ9APnN6tEjvX8r8W2MyMfq5PxgiaF/VnxFFUNX2FUFppac28ximR+gh/+Q0BYPd7yIK97CmvzZabyZ+Zumg0r3yqIjgLxUqpc4pv+U/MeGaS/BfYdy880rjkoFoPhzmMNeZo=,iv:fb1AQdSeAdF0Ba/d1PbvyTDgvY6OcQO5hjuuLg4Daoc=,tag:2KUrSkL89DL4ELgBmVg0zg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
