apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:H17TwPNI7JdJY3eQG4bSt+56EdZ1wh50uqhDVIaEhcRg4OtdjhrdB3ObNbck3QlPjnLDmfie38x5GOotTLKpdY4e7Fc=,iv:8TELUt28X9qien0ZauTR+YEHUmVXfRW8WqqVnAfL3es=,tag:pkoXqThij7ICmYGy/NbT7g==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:RYdtnjTMGer+Ib70q0j6/ahV5At7wsqI+0X4wDn94Sj46ur5vzwptmmaXmwBgqJC3Lxz1HY+O7zwO7apqJ1uIw==,iv:Z4G0EIx/Mawyanwg/DyvCUsjRgYxW23cpObUnCuyhlA=,tag:eh6ojKhoWdgZhPlZVIhCsw==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:puNamukgkNfuaFY+4ILLxL9CpAU=,iv:uzB3Sz3jceJ4q9f4KLTedunEqABqOCS4GZVml22PC20=,tag:hExpAytkfIuilVBn9S5Jbw==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:/H+b2XXPi8fS2Kqc7gf8xQzWbhFk2RLABQv2zUbiJ4u80d2xRbmioy9Q+g0=,iv:nc5wutySBOElNolmykbAhRV65FPDSf7uBjNg6T/2Fic=,tag:mvlLEf0tzeHRIDtwhAGkng==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:4VAG0th65Zo9cLUxmy6gkg+3wmMKQRVd2YhRMAltHg==,iv:YPEHqAZX+1Bxo+nwnqdXMRsBKxKJBlI/AExx4GQbY3Y=,tag:yaSY0HMcKViKkNYAoOBB6g==,type:str]
    AUTHENTIK_GRAFANA_CLIENT_SECRET: ENC[AES256_GCM,data:pqKw4ySI4X1ZmOphfi3pVP1MrHP0gJshv7+TO5+hN/SlWMrnAoEpECHMlVfc/YqmOKoaY8w7rySBv3WIN8GeFg==,iv:6jTSb5JndCRtSqITrFIw+wO9Sd1rzXuZrbB/RrnQdEs=,tag:LgNVfU6zTOAhZlIIZrZw7w==,type:str]
    AUTHENTIK_GRAHAM_PASSWORD: ENC[AES256_GCM,data:9Hv/wz2bjueXg/k3uwD1+yDWZ7g=,iv:xmZ5zvpdRwmNeaE6WxfwlOGlOycjBvZRnjF03swz/f0=,tag:q1dYrjJJO2H0uOh0IqSkKw==,type:str]
    AUTHENTIK_OPENWEBUI_CLIENT_SECRET: ENC[AES256_GCM,data:2tEZTUqwPhs2UNUXDS40Sw+MfZjWuzrdQcFrXTOoXM0xBAezR5jfFSTJ0ErgLqPBa2/z/jzWA3vRTE6v6z9wIA==,iv:2aDkNsinBcfGrHWkJ1a/OSZfoiuxfuGz/AqOaK2cgPk=,tag:v1GWucp/ZJHRs+Ayypi2vw==,type:str]
    AUTHENTIK_WIKIJS_CLIENT_SECRET: ENC[AES256_GCM,data:HUZ+TuoLVZx1E1f11KGohuhhy6jB3EwWM+DKpysExdPek1eJ18KZUfgo4Uc6kF2pNtL0FPgV227kyBqx1jrR6A==,iv:yRrqTuNgsDIx7GP6QS7WCnWGZBxBBDTZe4TCy2S+fto=,tag:jNl1WDy3au2fp4FXCrMGhw==,type:str]
    AUTHENTIK_STEPCA_CLIENT_SECRET: ENC[AES256_GCM,data:8pLSdMT4CQDB3GqOMUxsKEnpfDZ38BeujlVvNJkotmZldv4C/9kKQ2q9dANaEplU7riqjq7XsdXtbWmQmqmaCg==,iv:ivZV5DQFKHNNIw8/StktYn6DrvYYyAILFJh49yeslFE=,tag:FApAIrE6EGTZyiBvPJZm8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBaHNiaGdSQXU5S3hWdVBk
            SGZneWJEUHVCUElxVGhTMlpqY2VlLzAyM0FzCmNXOWpFTm54RUo4N3BYVzZMa2Mx
            K0ZXYzBvZUI2VmUxWUtXV3VzQkxiclUKLS0tIFBLOU5BbExxdms5SDZ4c2ZLdFRm
            U3EyaVJoOVpIQzlXNlBqNkl2YjJvbUkKVLbaEUYziHi9v1xdvkdpjC4nek1iUKg4
            O7Kepu2e+0HvcgKhFSD48UaD2rI8GU/39PjbRDIuEGjm5v7rfyKRtw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbjFZNUxEcHVpajVOL0xS
            bm9VNzI3Z29ib2o1c203QjJwaHlHL1BnaVU4Ck5XbU9yRlVld2tkZ01aZWpRV0da
            MDlWNlZKTmRnWWpoV05xUk5hL0tlOTQKLS0tICtqRFduT216eUxWYUFCaTFkamNl
            dEdKT2dNcm9ZaFh2NkMvaWFGZCtNNlUKOhDGyEJ83oLN862k6ouv0Khm4gpeZml/
            hkLixGWChHmU7pRCp6+d0MDBGv1W+JeRYcN/DdkyJrrPqOg/oh0JYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T22:00:02Z"
    mac: ENC[AES256_GCM,data:ShssIVIL5HxQM+IZMhzxzwunILuH9WCoA7zlazR3iXU0BcA+cGPAigORdAcZjHSgxyZeGf3YAbgpzip4KhDec6UDoUB7Qg+NR6kZ9NMzTEL2XJzA+sasUwOp0hBBVk5ENcB+Zy3OLpY1LgiM6+zDLctjbGrb0Kq/UdrJoY/srbI=,iv:p3soFe7fWcd6Xe/6qV65yNnbQD5YTysp/2Mrv8kRlWw=,tag:ZUVl+hYKnnK+TVb5I/UiXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
