apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:JSA1TgajZK1yhXEynOtZeZzx9Dv2ldGCepIjVCD+7aZ+1XrS9TQHhNaMKFaFR0MgWfdV5lM=,iv:53IfF7dM/sC193N+7FH8VfUacL2VI3Tc4RpRmuvy2o8=,tag:LZreFqUpN/vOJdUo1kyILQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTWVOUjBxSEtZMCtWTjBJ
            RCtoWGEvYzV6OWdkMUtyS1ROYVorczZqMldnCkxNSS8vNmZSZDA4dVV1SXVTcUY1
            YVBQQmcwZi9wMk00c0FTeWpqVTVON0UKLS0tIHZjdUJXNmd2ajJJNTR1NEw5Tm9o
            NTJhY2VVUmREOHduc2dtZ0hIYjU5cUkKOiUUVqz/X9IxiIOZippTkr6S71CsKAM7
            hUHAi3NMVTqm4iZwSrwOuoP9T7w0qgdcXzVQyjjWYEMri5nSpWuRzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T23:18:57Z"
    mac: ENC[AES256_GCM,data:jvxMKC6FHMb+Pyc7Z+fgXYY8w0PSmh/3n3voLGEXWYUWVMI3VkTD4h3VlJDhMq9o4/htGJupy1qzl5ee1fXrOb5llOww1eZJGk24ZQ/zdoVNJigr8REDzBpGa0ixKUdATC+gtadVcH74um/x9U03qHXAG/00kHGobayDHeH9U00=,iv:pMtjEh0qxEk4DgWto8B3glNUlP3+1JrEPg38Hiexqlw=,tag:xdqXFlKwtqYcZYLWjApMdw==,type:str]
    version: 3.13.0
