apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:4Tlgb0PJiHRnQCpK3AaTucUeJEeauRqNLqlqFo/kLYdfAPSPqwbg2nPtS2aoj+AnSP6qZ3U=,iv:CIYNteo9SsRl4+BSd0EMaMlbU9xJoAEjLPssp3ytM3s=,tag:5PPiEVrJZ4XwvXgm0XFvNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYmQrRkdScXd0QWE1b2RK
            SGsyRTZyUlpIdVd3cm83RHRIc1JHVXVpWkJNCmdQemFlbFhsQTZLb2RBaDVTWDdl
            Q3VleUIxc2xUcmxDM2NTVTlEcCtqdjAKLS0tIE42aURsdHdDTWZWWTlOK1NLQklK
            RjQrSXlHUE90eExzOEw4dGcxQjZVdnMKjftGKGzvsaU6YRaC6LS/gOYvhBSShdNB
            lILKUGBXuGYMSr0iBiu1Kbq93oSTIKlPI13JpHvuMcEX3s8RHbIvoQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVGNRTEEyalBrcVNqbXBW
            UmVPV0t0WWJXWUliclViL0hVTnkwaFdZZ3dNCmxaOWZzMUdEbVNLUVoxQTNLWXJD
            eUYvS0M2d1BpeVRJbFpVVGJIdGUvb1UKLS0tIFJCSTJHRWhEWXc4ZDNLSWZoK3JL
            SUlZb2IvcFJmVUxUVG5aQ01PaUFTZWMKctH+0pjKmVY4z5xI+VmldxFOXG7NLp4/
            qfRXJBuIFzBZugh1AH/isVD5D48yyIPKpqvwOvUIwwhDHbiSkktkGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T21:03:29Z"
    mac: ENC[AES256_GCM,data:ciiQHtI0fFaZ/N/q6kJz7+ionev+raB3z8MqWN538jf9hwkhN8637cJdtBFTEHGSju0M8o/i7gBuNofZ8/e1sQDKtPy88GxTsT2WcKfAwN2UmTEAv2DQ4HYMfjEFhdGQ6tJ/zy6E2VmwMHUdtxa0gDromSu7cQOgNN4oamQ5sTs=,iv:VkmHf31xTIRWPIV5+6E6Jlj5uzFdDtLXuE7WRjLleYw=,tag:D9JZUKvQjTRLqV4LDFvlhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.13.0
