apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:JSA1TgajZK1yhXEynOtZeZzx9Dv2ldGCepIjVCD+7aZ+1XrS9TQHhNaMKFaFR0MgWfdV5lM=,iv:53IfF7dM/sC193N+7FH8VfUacL2VI3Tc4RpRmuvy2o8=,tag:LZreFqUpN/vOJdUo1kyILQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYmQrRkdScXd0QWE1b2RK
            SGsyRTZyUlpIdVd3cm83RHRIc1JHVXVpWkJNCmdQemFlbFhsQTZLb2RBaDVTWDdl
            Q3VleUIxc2xUcmxDM2NTVTlEcCtqdjAKLS0tIE42aURsdHdDTWZWWTlOK1NLQklK
            RjQrSXlHUE90eExzOEw4dGcxQjZVdnMKjftGKGzvsaU6YRaC6LS/gOYvhBSShdNB
            lILKUGBXuGYMSr0iBiu1Kbq93oSTIKlPI13JpHvuMcEX3s8RHbIvoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVGNRTEEyalBrcVNqbXBW
            UmVPV0t0WWJXWUliclViL0hVTnkwaFdZZ3dNCmxaOWZzMUdEbVNLUVoxQTNLWXJD
            eUYvS0M2d1BpeVRJbFpVVGJIdGUvb1UKLS0tIFJCSTJHRWhEWXc4ZDNLSWZoK3JL
            SUlZb2IvcFJmVUxUVG5aQ01PaUFTZWMKctH+0pjKmVY4z5xI+VmldxFOXG7NLp4/
            qfRXJBuIFzBZugh1AH/isVD5D48yyIPKpqvwOvUIwwhDHbiSkktkGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T23:18:57Z"
    mac: ENC[AES256_GCM,data:jvxMKC6FHMb+Pyc7Z+fgXYY8w0PSmh/3n3voLGEXWYUWVMI3VkTD4h3VlJDhMq9o4/htGJupy1qzl5ee1fXrOb5llOww1eZJGk24ZQ/zdoVNJigr8REDzBpGa0ixKUdATC+gtadVcH74um/x9U03qHXAG/00kHGobayDHeH9U00=,iv:pMtjEh0qxEk4DgWto8B3glNUlP3+1JrEPg38Hiexqlw=,tag:xdqXFlKwtqYcZYLWjApMdw==,type:str]
    version: 3.13.0
