apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: technitium
  namespace: dns
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dns.wind.etherport.net`)
      kind: Rule
      services:
        # Primary - technitium-0 (high weight, gets ~99% of traffic)
        - name: technitium-0
          port: 5380
          weight: 100
        # Failover - technitium-1 (low weight, backup when primary is down)
        - name: technitium-1
          port: 5380
          weight: 1
  tls: {}
