apiVersion: v1
kind: Secret
metadata:
    name: technitium-admin
    namespace: dns
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:iK03rl12,iv:Q65Ctb3X78W/zMiEp7nvXDIStDDrFZdBvYnMIDZKe50=,tag:FeDlWWtpeJJLXAGCp3dShQ==,type:str]
    password: ENC[AES256_GCM,data:RnDEmgoRgT/JwnJbBYxu2pPO/MOb0aYHptDe0gJj,iv:fCMe+HHW3vtVRurzQ2v4EADywbWXZSupmk2ia2sVdGg=,tag:WijAVA26BxWx2HPo2yB2MQ==,type:str]
sops:
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJa1FUdXRvM1FOSjhVQUxO
            K2ZCZ0ZTTWZOeU11M2NzSWRYS29rVkd3dGlnCmpseWRodlRoVnRkOTJNcmRkdFhw
            cUlXYTExVnQyZGJiOGJFbWNSSG5OaG8KLS0tIEVaOTdmYlZxbVBsNVk5R0o4a3B2
            TUJwcTJrYjljREE3WCtjTkZzdjFCVW8KJ5vOZzYpHVqnf86TKTfF0PywGfTcXdKR
            7MFaQ/oia/aPMZQlk0OQ7t3fceyo6NeKbigRi6YAPPD0sC/W5VCi1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T20:46:55Z"
    mac: ENC[AES256_GCM,data:vLKknIO4X1OtwLzeOTFO8ckKEpUPR8iGbWiuAngNS7V9jMSQDdYL6pfvfRUI1Kxh5i62vcfl33npIW6aFWUHbgo+BYxAK95INLwo747n/0M2HpFDqZjA4NSTEWoxJR7hLe8ekiXklbHNSAz7v2Si7AQKcQ0QrJ/mLTC+oPMl7pk=,iv:Iafx0x4ZqQ24kcJ81xbh/PXgjwaB8RgLD987pvJ0sXI=,tag:xtloVykeIkZIyV38vhkqxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
