apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kopia-repo-pvc
  namespace: backups
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  # storageClassName: ""  # omit to use your default (Ceph)