apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kopia-config-pvc
  namespace: backups
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: ""  # omit to use default (Ceph)