apiVersion: v1
kind: Secret
metadata:
  name: kopia-credentials
  namespace: backups
type: Opaque
stringData:
  # password used to create/connect to the Kopia repository
  KOPIA_PASSWORD: "REPLACE_ME"
  # Kopia server UI login
  KOPIA_SERVER_USER: "admin"
  KOPIA_SERVER_PASS: "REPLACE_ME"