cloudflare_dns_token: ENC[AES256_GCM,data:UwJRoPIq92ivhJAK47nbpKfoUwnsQZ6moe901QMb5CCen3XO7lqyypWixgjoJepuCa4wHY8=,iv:2EiGi78HEuFdwkWqX51Q61+t32JJjkVr6NRDWMSHY0Y=,tag:3DWKXNVrzaBALYLjrT/6UA==,type:str]
twilio_sip_password: ENC[AES256_GCM,data:+zxBTqyZLayh/lCO8FhOCvdmhbxR5t4cfsprqXRW,iv:X9Y/0Ct2CjZ2Agyx6n+P9LWtQc0Hv/8BiX9U01x9+yk=,tag:BEvOg9FyiM5xMWTwfGr1sg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWUd3M2pTTklaVURuNmNi
            SzMzUi9jYVN3RG1aVklMVldNQTE4Qy9idjE4CkIva3dxU0ZmckZBQ1g3ZjhrR2RM
            OXJjTSsyZlQyWHR4RFlzUEMrTFhDK1EKLS0tIE1xS3M1R3lFTjFBbXArdWw3bEY2
            dlhzellqc1h2dUM3c0dIWFFsbFdwNTgKtJVbZx9mn9zhMw1aQN2RVxwSWH7rpKVE
            gOPCp2ys4ouJTjt7Ihq+eHmWuNYa+ZRFgxA68DwhWNGDB5cEet1oAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Z3cyQmExUzRWeG5PZEhs
            dFRXR1c5QnlCVm5xcjFuZW9KelJXR2dLL0I4Clo4ZzhveGpUUFJTSThTTFBRUGdo
            Nkg3MEMwYm5uUGlaQ0xDZ3l3Y1ZqRTAKLS0tIFlLaEQzY0pSSGluVWxFcVV0eE13
            WVh3eTRZWUhMVTZYMjZkZ1FnejBhbzAKZss2caTCU7rPcpQOxRu/p//44+7IUF1I
            giFRn5jalGtyddLLpq/qOf/RfbV3EBglS9eFnAMoEmrXgZW7rMur8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    lastmodified: "2026-06-06T05:44:36Z"
    mac: ENC[AES256_GCM,data:vrOUVelZS8KaeI1mjRyhHISiIXBs6ozqWCkOxgrbJPDcz6BHgkULxYFvURdJjxkPYi6cUsOtRGFSMACwD4sRObww19YgP1Q/2nVGoFRX+HyjZ6auFDgrK3xxCk/wi5toX/CdBQxVRTiZXwEgop2D1ffSysJrGBBmsr3hhFqNy3I=,iv:e+hOuvzQdKZqYwSXcPSZ5NjhsTDfTYCEE/tPe9kI2BY=,tag:f2fsbgULbQAe9tO++AqECQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
