cloudflare_dns_token: ENC[AES256_GCM,data:UwJRoPIq92ivhJAK47nbpKfoUwnsQZ6moe901QMb5CCen3XO7lqyypWixgjoJepuCa4wHY8=,iv:2EiGi78HEuFdwkWqX51Q61+t32JJjkVr6NRDWMSHY0Y=,tag:3DWKXNVrzaBALYLjrT/6UA==,type:str]
twilio_sip_password: ENC[AES256_GCM,data:+zxBTqyZLayh/lCO8FhOCvdmhbxR5t4cfsprqXRW,iv:X9Y/0Ct2CjZ2Agyx6n+P9LWtQc0Hv/8BiX9U01x9+yk=,tag:BEvOg9FyiM5xMWTwfGr1sg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Z3U2RmkvTzRUanJTcnpE
            T2FUNGl5OGRLWStTSENwbWxvUnloM0U0SkI0CmxPZkNSNm5KenVGS1lpaWV0NjI3
            UUpCQ3BKV1U1RFpLRjdLcHk2OFREcU0KLS0tIFoxdEJLT3c0OFBEWERDOGpGM0xP
            TWZ2bVhzWFNOUkROOFJjUjMvV2JmcEUKDJFAO8ANJajRJFGijDPJ1YTTmVQypU86
            4wGRC/EDcFvE0zNyZoTwjBRAcKoEN8ChK9Hr3dO8gSFNX3PLLWRJpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
    lastmodified: "2026-06-06T05:44:36Z"
    mac: ENC[AES256_GCM,data:vrOUVelZS8KaeI1mjRyhHISiIXBs6ozqWCkOxgrbJPDcz6BHgkULxYFvURdJjxkPYi6cUsOtRGFSMACwD4sRObww19YgP1Q/2nVGoFRX+HyjZ6auFDgrK3xxCk/wi5toX/CdBQxVRTiZXwEgop2D1ffSysJrGBBmsr3hhFqNy3I=,iv:e+hOuvzQdKZqYwSXcPSZ5NjhsTDfTYCEE/tPe9kI2BY=,tag:f2fsbgULbQAe9tO++AqECQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
