git_ssh_private_key: ENC[AES256_GCM,data:2syQbEwcMF691/+oG9LwFaGQYVXEv9R/RGiAbXU9HbbzfE9XvrWRl1s+xt3bKZNkvyZ8GyDXxvsCnmJXYzf0fCN9RObEgdBpwmtwwbF+7wb2zpMyw2aPF6EvYL9311dNHD96WjlSyQuoDsVRFHge6/u7PoOvbTJsK72DHw5TrbKrY/ibPlVH1NC+niENQQZtBXCUlwBfKMBrbQkkef1/0lHQZKVewq82H1ISVu422iVsLR9JjUsYALkIHwu1eRg/1Fseexgw27M8eRRW5UwPKaGglZbIsW7DeJiiYHCNC5DyHM6TM5g7DAO6eGr5M1p+zkBZpNniKH3/Cocox7Ajv7J5cYZBPKTwDlocmNwqOiraOJvPRZkGVxkHnZKDBKs0LlbUfrDYwv8L/bsxevMi4IYVTZarVJ9S/7nym55M21U5QUmAEZbY732HdA3U8onhuPpHZuy/3hD/r3UIp6a+zcIz3l9u+mGgRWQICbLGVRDI/fZJn4K68VS3rWzBmBLo6Vu6Dg8XbhbCvDYHYYuYAikICWdiMbE9zELV,iv:fOyY/RHRUVnZydc/nt1B5VmcyCNLKw7iSqYZJCLpbRs=,tag:AISv+r/v4JOj35zR286p8g==,type:str]
git_ssh_public_key: ENC[AES256_GCM,data:GdexWQa5YWaA1Q3HOGK0Fps1Cf6Y7RFOKRVS0ttgF1EyoQWHWPkTx1eO0JOHWX87yY0ej+ul9RiaO/3Om9XY9uBovsR7qmfEiryKaS6oZ8rM8KfA5eCAea/Onui47P4=,iv:zxHZxT86FLuR5ohAUPpKGo+zotJFWMTCw3WBnVRCCtY=,tag:o2ncFyLJlXO6JzbTHkRx7w==,type:str]
tailscale_authkey: ENC[AES256_GCM,data:nNY6p7OWOmO1Hz9OruKeCMYZKcP6YLunU8lb0wzxDGSQrRJvZW7IqQSJRnyPf6+BbKe2DLX94aWYOaR+ztI=,iv:ec5es/QyeQE752aqf98+n4hHHhBE+qsA1Ka20JwjY/A=,tag:8qeNG/ygdT4fc1akDEd8Wg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQKzZnT3pNRWJBclJhOXIv
            Z1dPUkRPbTRNMzVDbk9aUHhXeFBIbkFIUDNvCkNEamtobFhlOHo1Q3V5UmVtY3NW
            NGE3MzhSZGNLMjNCTU4yQU5nVWhMbGcKLS0tIDZxaXp2QlRSN003ZHdmZ01KMW1x
            Q1FDR2ZrMkdMTERMZkRTR0lOdkUvMzQKtiyTJR9BYimFwiRsOBM9f+MwLk9vX13m
            mclONAx9ykxz8oseA0S0VSgwcRija3RC3yRdfUSptKHb5qSu24DDQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlKzdHKzl6MDBKOHRCblYz
            WjNkTkgwU0tpbzVCQThhMUE1bzhGcFU5MlJRCjdwekRRTjFhZEZ1SzV1YzM5Vlps
            VDMrT1J0dFB2ekVTQWFqeTF0OTZzTWsKLS0tIEpocHEzMkNYRHZYRm5ETXFSV3R5
            Q1FpSWVHV3V4Uy9TeW1lSVV0U2p3NzAKLEg7xldB59QslVBb2rfgly/7izQV3zx3
            AXaGNgIsrzck6daRuvVnP77HeZWwbeyXltmmN+W4+bAeuHQehkRZ7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    lastmodified: "2026-06-08T14:31:16Z"
    mac: ENC[AES256_GCM,data:B9csu+GnCWtR0tbULOBMh7kUVCyfqR3Izx40IxnfoIh1XvzSSr96NnVP6yt48yV877vtCq3xIsxzI6qzViz9ngQ+yI9Po61PWZSvOADqp5BB8dWUPeqZkS5NlTZbDRznVSXzvrB+5OsHBp31W1TAQMGeejPQNtqpgOjUac6GpC4=,iv:TmYxommZn5SXpUlXxxIDdRY/M0Me5bpg1NpH7Pxl+rw=,tag:MpTFioD1ClR43EDmb5gtlg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
