etcd_backup_aws_access_key_id: ENC[AES256_GCM,data:+cd2HrtAfIz8Hm3Kb83E++x0IB4=,iv:uBaZsFaH0wu5xEh/fANMWa+EbbDTLvKVcG5x8IcpXJ8=,tag:whcyqgj8CfquTHsxfl3Q3g==,type:str]
etcd_backup_aws_secret_access_key: ENC[AES256_GCM,data:B0fzSWOXA0xMHjrEROgHfTs+vlae+9OE5VZj3pEJZ8uhFjhMFb55bg==,iv:ba4OyMO39GZakRJseXnAogDZhuCWap1Pi/Hv81QiT2k=,tag:qwEPNmEYsXo0iApGI4imFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaVZuU0ozYmpBaWVBbFpT
            djl3M1o3K2tpUXV2dkNrd3lua01GcTh6cXhNClp6V0FuNFpKTkVDUGdFeTAzTk4w
            OE95QUcvNzZsdGxYSm1HcEdnUU5RUk0KLS0tIC9IM2JSL2ptY3FUY202WFVzU0tk
            SVZtV3NXL0RqSHlQZ0FSbEk5NzZUSjgKXagjUuDOz0+YxmW1jMDZy5wEHkqKZQ9m
            3KS2FXl5wZY6pRFfJ+Efyy5pfgZRf1KvaKfChzE4LDzb4w+xmB29nA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTjJVOVI5MUR0VnpCaXh2
            WEcwWk12Q1BKcW9sQzR0Yit4cEMrbFEzZkhvClhXQzNObzdBZmpNOGhhanZ1WHNT
            MHhnU2REMzdrZWk2OEplRFJDb2tnK2sKLS0tIHFIcHV6YUZOVFZlejlJekZndnVU
            dzRKbzBobVJZeGpaTUIvZUNoMmFac1EKnnG9TXl4D1jmvpN8KYgHkiHVuGjZwN0Z
            pTcQaQQhdqhtrli3lX9ivSjQuGxvjFJv00qp99L7LtbfdyzpZu0IGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    lastmodified: "2026-06-17T01:49:45Z"
    mac: ENC[AES256_GCM,data:pJKnvec8UgaZrOj90eKcv3wqwf77YbU4FUEVXTdWhq40o5XILhHwl4YJaLXtWQGnxrg0USluw3YEnvijy2vq3aZHLUulyAM/BqjOClK56pa5vbOgbhvvpa2A35n9iDjLxBXrpmQ9ILPhpJE2R5t0KBJA471MRyUcWDNN5GZRUOI=,iv:NT8X11Lm0bsEzpeAlNcp94YnIiV8uTsPEUAY6HTpHIM=,tag:T7bUrXbOyRVpuIdFUz2HaQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
