automation_ssh_private_key: ENC[AES256_GCM,data:/sTGmpjcAJUAQQG0m9ne0XDSO/tq/M8N4yNIvAQLFmby1VRvCoyKRcbCrc8qu6QW0NrEVxFyLQanh/OyZedqc8Gm0WcwQxpccrFeyJcEhImKa6nFVmuAGgI0uf/sQkNpfheYceH5lLLnAAwsljWy5t78Nwy7tiJyp627eo3kH4JQgYzLLZUCGF3NoECfC/B27ZKzzoRufr2DKZJKZ9U4b0MpD5XccJmrnfzisjG8N/Od3pFuOPStdHrW9H+9pE9cVdQi3oULMRHofR94jLAite8q4ET7lfbnATg1ilU90ZSuCuoJGE3DDSvban6r3on0yxCYjZh+wT28VeID3yURICKpaHlZjzFQjkKTtTjFCg0oq17tef8ih36wjRI2u84L7Y6n4jp52JDX0qBG/t51jd8Z2Ko8hdTfqQw2H3Ko3xjYQsSlwX+w655mFaIxHYmOnXxyTeINyVnP44eY8hKiEskldbYKO7OCCTnfyUj+Fz680vdyBy/qvMgTNHRFUfzjc2ChkpXgsvr7S8iyvLrCmzi3gDS4gnAqY+b6,iv:ZJ2Lfn16zfmZQZNCDf8qSJNSuFtBX3T0MloOmsTEw9I=,tag:WD8gkV3ziBmUHLTpT9siqg==,type:str]
aws_access_key_id: ENC[AES256_GCM,data:jqla4k47GjUf4yNpd7ySK1VJPz0=,iv:PpQLQo4K9p0nydBETFGthqARu/zEqdHLq/C7q3ZIjis=,tag:xbuETH/QN+qghWlRWgoWaw==,type:str]
aws_secret_access_key: ENC[AES256_GCM,data:rlFj4kPEvJOavLYYp3L1qUG3dlr8RxHqa0iTOGlk+qzm8XBk+IBXdQ==,iv:QGP22y2XQhacqFEEFoeNm1XgKrPEmEp14g3pwdh/rSI=,tag:FjkcKFguKXT8cU/T8kLhVw==,type:str]
cloudflare_api_token: ENC[AES256_GCM,data:ByaC4DBmM+/xXCfpPpRArL9plQApPZlRKEouU2r4UjadfLkCWrDOqGRxMHK79XYO5RSBJV0=,iv:5XlQn/UoG/7lyJo7v4U/n+VeuexTwRj6NKyrCnpcH9Q=,tag:8b51KyLvFOim1YUU2ME7ew==,type:str]
twilio_account_sid: ENC[AES256_GCM,data:JqH/15eTDQwukDPQRLVIOmAsOQxaXhCaNZqAovs2fI/TmA==,iv:2zwa8Kf5YX7cQbDRZf0sPpCKBfW0FgdLAMXGr/jP1qg=,tag:ba/njYkn4bYVdPRPYLiYlw==,type:str]
twilio_api_key: ENC[AES256_GCM,data:P9tPjZI/UNXHHzL+Fs0oCDdsk5k6lrpuXRFPLd0E8r4Akw==,iv:YgRk/tNNtwWMVHe5yFQyXyjoeEzEKdnZV0drNcUznEY=,tag:RKlOyBRKXBJgN/AeIaG0Hg==,type:str]
twilio_api_secret: ENC[AES256_GCM,data:PH7+MqlLIMUk+wCVLgY7LlMeFb6IlnlWMHll45DorQQ=,iv:Y+k3s7pDG92sd6PR/N/1OdHF3N/kRev4jmRpZhciPj0=,tag:iJo3XKy70VSgYWAyqY9bLA==,type:str]
udm_api_key: ENC[AES256_GCM,data:L7WAJxw3DdNjVLBXX0AhsAp7IhKaYNTWkbu74Ogf8JA=,iv:/V9IxSMEgUw0jIoFKxRnQIRsuQGdFx9E6ujK93cmSQk=,tag:s5BJhOa1174oXjivHsCnIw==,type:str]
udm_ssh_password: ENC[AES256_GCM,data:X8gGU1RdIwtdOutrefvGGFaagw==,iv:HArVC0mS1jeCM7sPG5zJc8C0IdehlWtylMtFxAe88vs=,tag:ZT3fuGs4zCJqMJGD6TG0xA==,type:str]
udm_ssh_user: ENC[AES256_GCM,data:yappSA==,iv:moN7JHz30DxEOkVfOYoTf+cGhkFOVwJ1yJxRZz3DTn8=,tag:Yo9KZ25sE6/xMa/Z1fetLw==,type:str]
udm_tfadmin_password: ENC[AES256_GCM,data:8NyyNY/ruffT7TjDca89qDKupadxD/uI9OY2X/KI,iv:kNcm8K2R0R45uuhPI7Kma8Ee2ZhbvQJFN4vfbHIkn/g=,tag:BIxCoGGa1Bd2oakdiS544Q==,type:str]
udm_tfadmin_user: ENC[AES256_GCM,data:d3EcJZX5luM=,iv:EA0aHB+fVSs8TFK2i3iwqPdaSmuPXE/nOT4ldojCdDw=,tag:TveGSshYRTULgIGkU4XkzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUEtKcWRBYWpGdUVGRGJq
            VXpDcEhEdXl0c0JVYzNhUks3NTBjd3lJS2hZCkJwbXpKZlNsbzVPWFpTTmZQSTdD
            SXgrTllVUjUraDRnWHhKemZ0SHZheVUKLS0tIHJLWC9MTFJ5bHBHV0svVUVzOVZp
            WTRFb1JMT0xaWDlnVzZidG9talJTZ0EKV+miNCCWOBANJo6OGCEHqN/dKb7AnEVQ
            lbw/mxciE2pdHBONIipHIzs4BgoonHK4X8/9YciKrbfns5Q0sph/mQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcnp1dUxITGlRZFlWakhy
            NlBBS0FWcndFV3NqVkRSckJCZmM4SEtkSHk4CkZVSzhoQ2pjWWtEQXp3bXEyQnJX
            bnBNMDB0R0crdG5DSTk0d2FQcWkxcjQKLS0tIFhwSjJHNWRGMHZEL0pRWlNKeVZ3
            dmRNeGs2UldzUjgvMHZEdHNXZUVnd00KiK9yIaOkjZ26hbZ3b9gMAgeAnDxQALsz
            Q9ASGJDaNc3uDK+LfKyPpv5kyGnsyZRgxWI7tw0YypSUurAmJXjRoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    lastmodified: "2026-06-10T16:56:26Z"
    mac: ENC[AES256_GCM,data:qX8ARVjBGYdX2b7k0BqOUHiNmovB/7NO1ec+CVQTUPMgYD+hthEOIQkqmzIV9gIky+CNEaawTVQw39h+aLksKBW/29RQXk/0jQbJYoRUbveSwUkFAfFkAfznGTcljqVlkLfKxLoeAZ1udR1r3HDysUb8XGjfYXBanmjVp2bcdy4=,iv:mTgBdYwGnqMMaV143EysLqaaCSD1kKpnQbhiX7Gfnro=,tag:bkVY4231q4TIaAjmCdduWg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
