ts_policy_client_id: ENC[AES256_GCM,data:LcsqeQKxVay/rTLCGA+S5vY=,iv:kJ8BAUBv+SrA/wAHd/dgqM1GWcc/CNttiTqniRAbYtY=,tag:PTW8oiYDkc/1LE1yuSpoLQ==,type:str]
ts_policy_client_secret: ENC[AES256_GCM,data:XUOz9/cc9OiFkBCCyxP8uki2Oi2ox7DvrbQF+gqn8s8/os97Pdms5LElStaImJzKDJD7UbNHq0KwkeKyKFhJQQ==,iv:dRj8AgdKnWED8Xhazo541uhvoQ+sl59tQPCIYyu90Is=,tag:owre3UwRrMhCTtXtTpv1zQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMc1ZnMms3RVRNMnUxZ0xD
            K3Q2QlhEZUtMMjdBRXhkU0lqVk93N1pWa1VRCmp0NC9DbnBVdjlwaEl1cW8rckNY
            WDZxNEZPTW8zdGprVFkwbEU4a3dNc2cKLS0tIGpTaW9QTjJ1bnpEaDU3QWJyZWRp
            Qm9UTzBVOENZaVg3QlFLQVJYOTB4Mm8KpQkJ6KqoTgUpG/nv/3h8YyOq09aLKOS4
            mYiDqkAGmjNtS50JYKNARAj5oOuR9hAjkEkOVZY7B07gdHgwS1gjzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UDlmcU1ZQzFuRGVuTFN0
            SnZkZWlXQzNoN0Ywb05ZanhFelVnTmt2QXdnClQ4NjQxYzJlU2RGNkdBUFYxWThq
            cHhHNVlmVFdnWFBXNStRdUlxdzNaOGMKLS0tIFc0eWZpb1Jyd2ZEeFZYN2IxUjdH
            Q25oaGIrY0VHOU9BR3o0elhWWnlaNWcKVVb/7HzlWyhPze0Az3DhXWz1mReIk95X
            f0QSWycuj14ojQImIuh0MAgALgPaXAVpSTFFRWvNr+eWeeAU18RCnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    lastmodified: "2026-07-28T21:47:24Z"
    mac: ENC[AES256_GCM,data:izqChI4L/wdhjC3L3zD8pPslPHqrfM6ObgOaS5+ABHS4jUS3+iFMDRt5fEo217/VGjubkg6uPLjUGM9z2chOtzP5yCEpk/E/zbfJINTyYindz2f2XP9McugWPyQ2FbvjN8g8Fj7MsDvA5Ua+5W8hFU/Z42/hE1JQ0QWEZmeTito=,iv:1ftdTU98FBnl9CNqfC6wUd1MWgteZeXpBwm7iqftbBQ=,tag:wHY+btrFJWIwffQeLxv+vg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
