ts_oauth_client_id: ENC[AES256_GCM,data:OBWyOemn/lJPQ3moJA55xQg=,iv:0c3gMk0LPrBC6j15KfbQm8ER13grqu3bg4CppwhzjhQ=,tag:F+YXMBHifswmGV8hXiYK2g==,type:str]
ts_oauth_client_secret: ENC[AES256_GCM,data:E1MlLmoEtgdEJmesO2LdMvs5M832qb3VU4ZBBWH7wa9kahVaQ2XwxaJsrreB/sgQsozrKPWSoWS0BPCjaHrbOQ==,iv:ieFmUGNZs/GHNEtWAx3Vzf1LzqucFSaVQFY4pbV2Cu0=,tag:OmwEpzlEblBImDCKFIlWag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbStzSjlDSUd6NnVBT3Zn
            OTFNQ005dzVPcVlFNFZjUzRGUGdkS2V2QW40ClA2TEVvcnJiWGREL1lSUDVPbHQy
            V1VqbHNXTldOcEN5OFIrMXU4UDhxWDgKLS0tIEdaSW02SGZPME9pd2M0TVZTd25t
            cVk5dmlKOXQ1bUlkODlFdEJRVnQraHcKZcGMBlqGMG7ppXz19s9hegaa309LYb8/
            tvpw3hGW+T4Qd6NVqddDqf64z1v38KeDFYr7yOw3QfTgh9p5+gb0hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRGQ2MDZML0MyZVBVQW90
            ZTlCOWVhOVl5czVpZFNxQzl6dUUzaTF5c0dJCit1djZhMDlSeWZhZ2tNN0xMU3p0
            MUcvSzlIOTF4YkdCQkVCYk1Rb1kxSEUKLS0tIGhURXNVK3hrQnU3WEVHSm9vdUhG
            ZmhzbXhrbnZObFZCVkEwekFXc1p6b28Kw9RKsoWvVjshAHh+0WoAFZnAJ1qF29m6
            5wr76HCPwLTy+P9ApoxiANGzumcFyABi6M8XMs1lsVKZLwQSpHdS3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    lastmodified: "2026-07-25T17:48:52Z"
    mac: ENC[AES256_GCM,data:PuJvgBTK7P8lIea3d1ihRKh5zdVnVsVkaT9sUv+0AJNfbEbmtttE090VMdv9pbv0V70k+wPydyZ4JzZ7u56m4GFX833lNMfU1LDx2ephCgnsksJEKC+YVDwllV7QZ0bgwfMZA6/L4ANoE93y5vLgNJ6riCCD/MReofCFzfSUwS8=,iv:O++qq0imZS9dwF6w7guC+HCs396CTjINF7hXY+LbgS0=,tag:iV6Qc2IQ/bsR7ZVlTT4OEg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
