apiVersion: v1
kind: Secret
metadata:
    name: aws-backup-credentials
    namespace: backups
type: Opaque
stringData:
    AWS_REGION: ENC[AES256_GCM,data:VNE3yiKMf8fa,iv:7qzL6sIHmuHNeWKzRuTsSzetoK/tIkPlD7u4gSUTWG8=,tag:nAYnAACrwfQoCVbH79KxKg==,type:str]
    AWS_ACCOUNT_ID: ENC[AES256_GCM,data:66MTvKjXLvnVNULC,iv:WRoloBdpDrK09KtayZI1ifJPgc1sDKbtlBb6tUJliX8=,tag:8DodjALe9YadGcL5/Op7sA==,type:str]
    S3_BATCH_ROLE_ARN: ENC[AES256_GCM,data:BZmY1Rc9iBhCBbnFeCbZjkFQgocGYdPi2uW+JxGed2kuqUo6A5u062COjx1y6hM9ziqHATn0JB3T,iv:kE+b23u4BYl+AKM37qHj+rfbG7+atuarFXOf3YW47yY=,tag:UX9Hykfoi/ZlZO7QR5+STQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:n2toA2cXNreFCn5ekbSrtrcbiAA=,iv:3OpbF+auOfUmQYNF1jToI3RygY5yqZByTKTdhhSZiv4=,tag:Y95EKO+fraHxbuN9OCwhqQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:uR6TDjH0XF143URIpfu0bsGXNe/Qhch9a3+SV3L57lyqftw0qR3f0g==,iv:HMP+LdcuxbQFJsDw/OU2IK0c/QcdkqhezEs7ifat2Ek=,tag:gR4DHyyQDUXR1FlPn2ud6A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDL3kwVk8wQXdTdWw1MUVQ
            WW1PdmlmWXJyRGpJTEhjaUI4QkdaZm9JR1dnCjh0ZjdGQ2M1WW4rK1hPVDRVcDhW
            L0pxSFI2ZjhENWxlUlVtM09qck1nUGcKLS0tIFBRdTFPd0VzeFczY1JYL2J3V1Rl
            Q0NFbHQ5UGJhSnE0eS9DUlNxajhSaE0Kp8Ih0NeDSbtnQ1JXKERzT/kmvm6d7FRw
            4vfVeXtls0Dj1os2O5A6+3Ifiw1PQcQCRToWrO4JSXDmNP0Jwmf3Iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNXdEN2JOd1RhdmpnbGN4
            VWp0TDB6T0VDaW9URzRnZjBMa2ZPNmI1YzJZCnBlMUZqS0V3dmNRSldTV01VaEN6
            aVF4dmJtOHI5TnJtVEhwVDVGVEorTW8KLS0tIEdUdFRocjl5QllxS2NJLzkzMVcv
            ZGs2dk5jMytITHEwakxSS0NHcWlNMHMKjfZQri+6zd4USNmFHs/G36/qvXOW7BYz
            m9VkFparV0Ha76580JWSNl8Cq9DI4MxBW+891QEygVkVG6WB9VOP+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2025-12-26T16:41:35Z"
    mac: ENC[AES256_GCM,data:cjrLHI5rKaU3MUA8nE0VPxYpTCmoib05ujdyulcPy6OKU+8o1UDM08++r/cCFrafvFvNrywdkcOh3SVkrqq5D9lKgXWuYeG8bZKp5Ct+g3IH3/J3Xd3iHRM60vPq3zUzxEzCAEXL0kAqqPI76latanzynnd2O1iZkDSkNi6FIqM=,iv:ySakh5zcQnVwq/qZXCdLBqDKtC2Rtgg1OLsSVklx2s4=,tag:6ksLd8CRdMsV24dPd/ERHQ==,type:str]
    version: 3.11.0
