apiVersion: v1
kind: Secret
metadata:
    name: ghcr-etherport
    namespace: backups
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:lkuQ4RJtbkCCzQm2mFJ7h8ViANg8tZq4CMbHaktEqFGUwrnWSHWx/S/J7HUzMzU1QgSgYdW1EiOAOnkvP9D5o19DasG2IixP8wvYttLBBeJToQ1JD24VsBV8OOvtab6asATDACA5967B9gwTEp678h89Eean9I/DfYLH14I+pvZ9X5Ug8I6QmWedURNRDxoCaOWrV+bE6ewOgj2ZJSS7V/Yaj3jdAYBVg7V1PaULGxoVY/46O8l6O74FWIDhrm23QVu1wh987xVaKYRVAnw/gH4tcobHDEsYTgZOVZQSgvo=,iv:Djblrasca8aSCD9p3YuQhg6TeBcBU2YTNk/CQrqC2+o=,tag:i78DA432LmiatH8gHlhsdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcnRNdnVOQ2xtQW9jYi9r
            ZE5Jek5xYVpHNUljeURiVUpIVThMN0s2U2xvCmhlbURhNEJmbisyVjFvRjFXUWRn
            YkpyYm02UGdxbVJ5MEdZbXBMcmpCMDAKLS0tIDFJNHZiU1l0WEl0N21PbVJmMGFQ
            NkEvZk01SnoxdXd3RGprZ2VNR2FZYTgKgy7k/B9zYBhRsafGpjN2ot3MCQbKhf9J
            Q+AwEQshWHT0DTbLQgosMvTBQCQpqtyGok+FiGW3cfkfUq9iNNKQWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhL011dmhKNGQ5UXIzRWln
            NWs1Y2pkOWpwYWNGSWhjOFNUN0NvRUtWaVVzCmc5NjJTTVh6YjdFOWZjeWU4Z1lt
            YXhsUVFxaXhmcjYrSDZHQTlHa0ZKRmMKLS0tIHNRVHRaemRnWjd4V2p4ejV4YkQ5
            NEZOQzFmenNiWVM4ZG5sWnYvSUZOdkkK3t2JFcHLDGMc872XI4bf0lBv7KwScVNR
            mASmnhw3GMxh3wey6ojVXyi8+dBJUjJ4KmF8Fcby15x6vfD/vrx9HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T07:37:07Z"
    mac: ENC[AES256_GCM,data:fJ+YnbHSUZi+2gCa+YTjtCfm+kyOTwZR7ebrghRZ21jsggthmXnL/PQhbDg/vK/hE0EHL1kmbjNJB3sUWlnMdSCAToidsiryGmjRELikkuOmyADCXgaqJ8wHFgpD8MV6j1CQfekpRJwYqYNEvd3995xEdCk/LDikOfU0J36E4K8=,iv:GjilyWcI6hJCQHDpof58aebU4jdIZ68eebK5tzSTvL8=,tag:JsucPPdJrhbYdKCVulW34A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
