apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backups

resources:
  - namespace.yaml
  - rbac.yaml
  - cronjob.yaml
  - cronjob-email-summary.yaml

configMapGenerator:
  - name: aws-s3-sync-excludes-global
    files:
      - excludes-global.txt
  - name: aws-s3-sync-email
    envs:
      - email.env

generatorOptions:
  disableNameSuffixHash: true