apiVersion: v1
kind: Secret
metadata:
    name: wireguard-keys
    namespace: wireguard
type: Opaque
stringData:
    #ENC[AES256_GCM,data:lHutd+dpbwjV/94QWjzDZ3MnjKTwnBXcfEtstCAXxpKBOpu4h6Dhd7GM/Ne/Do5QlIIr,iv:E8UyLPB4yXFRJZLDqY+qBS+WXdrjn/y9jMqixEmPlp0=,tag:tJjv7eGezOLanLc1Q6xGzw==,type:comment]
    wg0-private.key: ENC[AES256_GCM,data:V0tX9RnfjYUk7xWpADl0bbVI+zhQlntmRbLJ9TMQQYQrLnoIjvqjdcEXVfI=,iv:zrPwizKxtU+e/AuWNmRkR/RYNfuMkmdTYExlEki+op0=,tag:tvsuE4yCI3yKg16mEy1O2A==,type:str]
    wg0-public.key: ENC[AES256_GCM,data:wwcYPtDDXnRK5h8ABw7IKdxqlm59KG3YCnOn9VO8hNe/JQ8pUBBxBtxcpiY=,iv:1Kz/j8eCDJq9tc6Z5LXSnnEcDIKyV1hTs4cn1BPaj5s=,tag:YWp64NNuWoproenh9cY1Hg==,type:str]
    #ENC[AES256_GCM,data:34BFNWDHsW0gYNlhbkS7LSq/n6Cz4yz2tsAg9r4PNrysD2sLZRDXruyTXH1tKavxIy3btiE8KuZPT+z53525AJM=,iv:to9py3fHCm4mzl+hyvEfoyID7QrmcBw7YIM6zqx6p+g=,tag:pnmTLTBN7A+36x77kA4wIQ==,type:comment]
    wg1-private.key: ENC[AES256_GCM,data:fNjEBh30S9esL6K9UWOTcR36+sb/WKON/2qPG/mqP9EKjSRtBwfrzySnMBg=,iv:3wWkTFVQIR88rkkzn/FbSA4do5w3DUoaBQQbEzAAJK4=,tag:niB3G7xK/FBnZBNnuaOVeA==,type:str]
    wg1-public.key: ENC[AES256_GCM,data:0RIWPaBDppI3DLPMhnWJzMsEXnsusuTxLAhOD6CRhDyMDwO9tnAUHTtZfjg=,iv:W7o+lyIeH0xmN/K1DC4K1qIczgYMrr9xdfKGLfv+uQw=,tag:SIiENVfl6dwEQgG0JgGpiA==,type:str]
sops:
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudnhSbWhxeWZSMmFMOFB1
            aVB0M1MxMzFtOXNIY1V1VlZMR2JLMmovcWtjCjBUSUxaUFMvUVNGcUJHZDFzK1Ru
            cFVCQmxEWmZLQ0p4ak5YS2RkM0tEVm8KLS0tIFVkRzBxSVJYVlFPRDdsL3RKeUc1
            U2FiSkVFaUhGZU1EZCtid3gzbWx1NE0K+2mUyKenF4A4YzzAfsdtaz2bEcI13hVW
            bgSBNn+4Qj4JGSu7zCdKknqTL20PMVtvU5DLnFWXid/CwQ32SSRgJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T19:32:10Z"
    mac: ENC[AES256_GCM,data:AZivL+xbfMz7FS+VSmj8n7IjjoyqnipT/gftPxVTAKlYGZC/5oGQyeGPrqlDQUWjg5u/8Zkrbz2pZJD/qZ29g5Htf0f3R+0hHM+F7hMBjrBcPLgg9grK/VdYUVc1+DhwNTrxQJY5ivuzNZRW2Na5/fyV3tPlAYJ1dR6JZFk8Dg4=,iv:IwtWTbLbE+lVnZJL2AzzgeO5En2ek1LpNciKTNclf3c=,tag:EttANKbGGuGT+nn7UTwvAA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
