apiVersion: v1
kind: Secret
metadata:
    name: wireguard-keys
    namespace: wireguard
type: Opaque
stringData:
    #ENC[AES256_GCM,data:jN2lk5A3Gu1WYVO1jFjm+baLHfn46G+/U0OcDfeP/sqyzSmkhcCUSa0TOkDKSsVUhan2Ll7b0qPdX8A+,iv:45ylTR4AVWyBZoQSOTrnwDF2EGPeGH2ICVHAVAjLiq8=,tag:kqRX44Q+LaRiGNB1EWm8/g==,type:comment]
    wg0-private.key: ENC[AES256_GCM,data:p1NqituB1/1r2Zofa6ZaWhI8HWlSwhPy+CMmS+Mk0Er/RPIq8gv/E2TozLM=,iv:5JnrLoxRs0DsdwW04nMKxNKkxfCKFtJ0Y/W3fqXcIRE=,tag:DbvZHn8YCp4gEBMGztOYhQ==,type:str]
    wg0-public.key: ENC[AES256_GCM,data:T5EEWVSUl894m6G0kKAyEGchWrdi4KnRdReZyZ6zwj5PB01GTr6SynLOlho=,iv:CLZYvaqtMY/vkpswz0ykyoqEz2hpWzdmLOq3cuSlYJE=,tag:qwmbliU0bI+ltxAdFMzRGw==,type:str]
    #ENC[AES256_GCM,data:3wQUm5q6Y3vx+f9HRYV/IolOpc8OuoPj9oBau3+t+cSiQCKc5F85yz80yi4=,iv:7rhj8OQpHIoJMopw9XQ7IYfvbZruUupbQYEJoAoLRP8=,tag:LMh2Z0qGwoSRZqxHORHNdA==,type:comment]
    wg1-private.key: ENC[AES256_GCM,data:jtEPsLq/nNRW2hDx7tI2ttrSLjhomjMVRRkp00fkz+fwLLfRVt64r7CJTRQ=,iv:KGnBQAscNFF5ke+CdMAtncC+D0QKX40lbwfG4bIDjko=,tag:sgGebj+vgcvBRXS/jOq0fQ==,type:str]
    wg1-public.key: ENC[AES256_GCM,data:d+4SqhfWTz5zy5VOH1Q3SNrm//IOlooZUrtDmp5WxMIDhZbDduFBeuARXJc=,iv:0mDaDd0HFZh+4BEBqjIjDhx+QAtnbJG59N4RiNtViHI=,tag:rcfkfXV77o8/bkzviTfwkg==,type:str]
sops:
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVnczMkkwa25WN2ppQ3dQ
            c3J4cDdFVGQ1czUwMzVnbkRPM2lkdkRpQ1RnCk8vY1phY09mb05PTW5pT2tvbm8r
            dXUzYUE4U29ZL0FYTlc5clRhT1VLRDAKLS0tIENmbzZ1WGZlMUZHd01DY2Ezd1p0
            WkdJNGRFdEFycU0rR2x4d09RajcvdzQKsMOVBnepdP9wkxvBqUuvgGgVvnNJZ9Rs
            LznQUCtM6t+j9JYhFx5m/5RlikuavmXW1OSW8CshNNfntibY88wXng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T16:25:51Z"
    mac: ENC[AES256_GCM,data:PZPKNHnZI0KLI+gasZJKNlsuqlu7h62eegnzcCBFUB2sRtNUbvpMryG5ke9DQQxCdzIo1fbVrSpCaTd+ynyqbRF72V3WP6ZazxM432us4rNHo1Q1Hcvri/SSWZUmyCDEzQwgXw1arQT1K24JrmHi/8rNIMOGdIjVLh+oXCJzQjA=,iv:VVih/OmpuzxKxAPoSJqSlXJ2/DR2MWeHsjT0QmDYIhY=,tag:KA7kFzJ8JvqWm/q22/1ppA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
