apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-smtp-config
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:8XdZppdO2dzNPdpj7L2aBYUMEqQ4L4Erpf2CE9lUNOg=,iv:iDYg96XdJ5xgq2MQuL4eCmXbnvStBoQQbHg3z/bajeQ=,tag:VeBMK51UHmuAfOk4nK1wtA==,type:comment]
    #ENC[AES256_GCM,data:lHygHuISGpGw81mviBd0UYdxO3W39vkYAXJRvdGpqIV6VxaEVQ5PltLRv2Mt1YA=,iv:Ae5NrWHzsjOSMbeYRIT3lGY1SNsZFBcRKZcye4y3R0s=,tag:X2EVMl9h3saOWbpKl/4GDg==,type:comment]
    smtp_smarthost: ENC[AES256_GCM,data:8VvEF4N1dZrOUvFDWuE8CNWwtMEx9orwFkDuBme3YTZIIfeRVxE=,iv:zNq+69TBIyCKKRcVATFZuf5Z7mot11tGCMEygIvSG50=,tag:1rIK+6rBQDeOVWcu0qccww==,type:str]
    smtp_from: ENC[AES256_GCM,data:U26R5nLu093bA+z6jsliR6t7hJsSdDZNJg==,iv:rXAY61iXC4iSSZnjob0A6DR+uR2yAvzMqvnBYsmMT0I=,tag:mLCUbBI9nBGytBuVN3FLHg==,type:str]
    smtp_auth_username: ENC[AES256_GCM,data:z2sHV03zo2+eL+ldyot8YBSwtYY=,iv:4Oub5+O2QnfkeY9D90KTU3wfr4s3icDoLOnl/VjCe10=,tag:iHz5sUm0CUMm/1iB4pXCqg==,type:str]
    smtp_auth_password: ENC[AES256_GCM,data:KwxACaHEOKypfq6uGWDDW739cFNsANVVEkFvR40S9x5n+Z4wSAjeoTszOoA=,iv:6lb5HGd/JhD++ABb1IQPzzDlsfPoz+HAwpztUiCfh8U=,tag:HS0BpIu5zh5RpyK4TCjPcQ==,type:str]
sops:
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNM0Z2c0Z1Mzc0QURrR3RT
            UFcya3M3NzNNVzNFT3JMczNBcTIzVXBkempBCi9xVDZTR1VvQmo0RDZOQjVBNnZm
            YS9zSFB5dmZZY2tXV25iZDdacDQ2eXcKLS0tIEc1VW5XaEVRRzQ3NGk4TUVVUXFU
            OFJMRmRnRTY0QndpZ3djVW1GZnZVY28KuT50SDJVmyLiVutWObdcHOkZ3r9sgFyn
            up1ORjFdb+6NNyn5RK5WUHmTszY21aBU0Va289C6TeKJHM0SG2bSDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T04:52:44Z"
    mac: ENC[AES256_GCM,data:D2PPKCTLWVTvmP/qy8ayIFhvbtNXYESx5lwSNjIADoqt/h7OogS+IIhuLOAX4BDBsONwfoOuHxuZXswxMIe9TE7t3Vzp+5TvBkMKZfbUfqXij+v9yrEMsXszcNrHClIyePSsD46fECpUzt53HocR9NH7eZg5pDNgItAHOHNQyzM=,iv:j3uArt4pSJpOpQdhIf58rbnhKiPXtzZXOEqZDT89W98=,tag:Wt+eBx0i584t2fz2IokBLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
