apiVersion: v1
kind: Secret
metadata:
    name: cue-ghcr
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:GQTPQA+8j/O6gBpi40GgvXm6lO/vtEJJdFLRrUEBpksAaZDQ/ZtklBBYO0ekiFp7FHJ6q+oTx2ml6Eb8J+0r9Gwxgy0/CTTLsWx/7nOh3EoMAfJBKXDGKO0kN8pUw08BkZIwu8eNOkPBQVTaAab72Iohzr6jpndBmtu849S59vZALLWWE8ztbD9spKSDhw3TcVEUYvPe88iKnYWf7G4DGafkbJNBCzlGz/+N059DQ9T84af0lOyEyGqc2XlqCiZ5Z7+if90vaE76NgfZ4JB1s9QWURxfVIX76hOFv8GvA4pyn5nyS7prrxEDIQg8D0PjxwfaIGhqF2sHBYb3qUo4c689NjCyVWE3L41uSm+QA8t3gGrKdwGqt85pfqzbp11vqzsNzxejelUzdd1XdLxvlwXISdbMuLZb,iv:Hc8VwlV8tj+TrHizkkkqJ7ljKEktScFCZ4JrSUWKDbQ=,tag:cMhXeGEQ/kF+3fQjsiFNIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcnB6Nzg4SFRFUkE0SU9o
            T3E1RUllWDROZmVzNmFFREpySjcraVZqdng4Cm50NUpmV0o4c0FwM2l4VWQydm9y
            OFJ5QWFLQ1dMbWZUQzVjK1RmcERJWUUKLS0tIDNBUlNqaXVXQ0tMbnQwRmNQdFZO
            T2EwRGVsUEZ3NlhUdnZObFU5OUdEY1EKSJy1+2/VzbV0DPNyCCAl4t8RRKHkD873
            JHIP7bzDkFrMJxPA1WT9f5zhYvZalIE8QagjfX6Wn2zH9uSVq8FSJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQ0lReFhhSC9pREw2bzRq
            clE3RzBMaUpodlZzVmliVjlEdTYwYlVEcHprCkpXeUxGUmc3bDg0ZlhJUU1Md3hG
            VDBUUUwvL05pUWhTV24xVloybnN6ZzgKLS0tIHI1RFc5VFRnMUVST28rUUdpQmdC
            SUc5SEJsTDRNT2FpQ0JpRm81cXNNWWMKtsSwXAxeHVnwZt1oFVVO1TrRk+rvxoRj
            VHEq5HPSylWTHBx/UzsJT09h46xgL2n0F/F4vPoMB76RJ7QQjnu3SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T18:43:59Z"
    mac: ENC[AES256_GCM,data:G9XjmFtHdJ84GIhfwFZT32o5cQU6skuFPC7Aw9T13/sIEsDht7qIO4dujHhrbC2Xq9nV54j+avYdoobIVc9fyzwphUDl8xIyQ5WBcOtlnBaWNCzurCS/Ucufmjup9GRb6llsX8L861zjDujSg8KPj2EmXannuGo1bzlkUJDOKFo=,iv:YkrQLq1ujk2n/m0rjw/5/QLOGlM332euMR/LnnbwkOQ=,tag:TGZba8yJGbBL1ckZxMDrXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
