apiVersion: v1
kind: Secret
metadata:
    name: cue-ghcr
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:q3bjn1iDlPALfRZgy7IcdauQFuU7WfgrlxSmU7l+sxLpPYHgDm/5WQOaTVWJ0P/LAXH/OWdORugIlK/UpwzKI3ftXifrlMOknB6/s/L6vkfXy8Bog6ih1kvbkFTn5Elt6BHbkB6SyzxGdF7ZzN1Aa13idXj/80kCaKgkLFI6gbr/cpc9mpfoGS5yWZsBUcLSq+upvKPpfEMtfug5nKYtDkz9b8MbV70OjgPyYy0jMJO7bxS+ZEkIwaAxBipITF58uWoLjXpwBb9FKBF98gBPtObT+BfM0HGYAaOBwhJA9NXJWAbxTUl2a5hYz75yw5SMXaibQWZS6Y3KzJ4LChV557v3ihxM9OnwlzQsEMtGs64iK0QYmP3tfdjnQXTwA6uT6jZ0pLwGspeTrv7D,iv:NWm4p9dtWJJL7f7VR96lusWZ1asIQjk5lCXUEOzKNFc=,tag:U256O6+PBEfy3jEf/4V/lA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNHFqYldQRjZibXFDUWdG
            ejVWK1liN2RpcExSQ1RUVCt4MGVqcUIrVHdzCmZiOXJOUTEyOGZCUjBIcFNmbFdF
            ekI3amRMN1lQcWhWeU0wOWtZaEZjOHMKLS0tIGl2VFdlQUNMb3ZrQ2pvVklQSk1s
            cUJQOG1Vc2VVWXdDdTMxaDUvWVR3bE0Kgx3sSXByTrSSo4Vz/eRAcU3p8ZsBfZ1z
            EXK9+4DXrHUs4j7fM5Fq/Smv/Wlr/U2kRf7f3yB3sUAWI5z3C653xA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyM295RlRaZkpYREdYQ3Ux
            ay8yWWFSeWtNM1UyaS9lclpyWHI4ckdhZXdZCndickZLaXp3WXVHVWV1TmdvcnA0
            Qm5kbEdIYm1UY1A0OVdrVmJCbytkbE0KLS0tIGMwNVR2STQvV0tEdVhSbGoxdjR6
            VnhOVzNJRTdyZE9ybnFmNHVZOUtvZEUKG5rmFkawD4B/+hi1e6tcZmIUkuYNy+yO
            h8hvyRAlnsHFfjmJRs+90H2pNuX5BCxe17mjvPooQDZ/mYQzHbjmWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T15:55:41Z"
    mac: ENC[AES256_GCM,data:hbNraqMKy5kfc7un0vIJsB6PYRNDgESIMcfPTpq3MsMECGKSBzRax/XJGt+/NbK0Wtfl+iewYBANYinJa7bCI3S8DwFVcmZ3An7PTBdhFF50sEJTAI9P/MH3BZPlPON8l/mdof9SHLW0LYATKodUMJhbMxdWslgBpgo7WvFLu3w=,iv:grHXZtupXalaqJ2gjjInS/tGg82kRIf3nqSyEbrP2SY=,tag:rplo2nKH/RtJ84HmT/5ciA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
