apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:2oHviWx5eg/wvUcekWQVHEFK85pxQp+CabmqiDnMZLxMvwp80STJVdzoOWF5krvkZtaX4dnv0gS/Yd/lWOhHZTHI7X/0JimtR6CBKcKJIybi5PX+vUS2jhoKcEynexNZxFHJ+ZFuvBLf9wbpNb7z5FWgr/KyKNOhDh1xEqaWkHjOIRki8ISD5eI/71/Qm7EPdc98RSrFCUjFbkIDaLjjeT1DD64Oqz6BfvZeKt60lu2wqR/h2LJhwA==,iv:7un0M9JHQ3cx0J/Ofcg3Tq5EnrLjbWvhAKbVfyglU48=,tag:IcyLSh9h2YDoYJdrxno8Tg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSmg4TkFWWXV0VStQdzdq
            a1ovQ0hpTFNhNmpjRzFwRmx2ZE9jcHpVbEVZCkZJMTE0UllsVjZGa0ZiUXJ6L05Y
            TlRTcGhNK094ajdDS2NFSU1YR1pGeDQKLS0tIEwrU29ySFpDYjYyeTNWNjFuZ09y
            aHJVWUhoWnRuSDZBZGFLNGJhSUM1RUEKK8hikc01jedeNBc8njqvZ6ae4QFeThAQ
            THhMj7yEObNBKGy9AJ+6u9+ZliXolalhVUPn/nKI1ugX6YLlJz2vOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T23:34:08Z"
    mac: ENC[AES256_GCM,data:LQKGsxysXrTY65VtaV7nrK90sQ8JriS6sqbfAcuvS2cU+FwBU8ttP8SpzOEKDF0I0us30RfMDE2Dl4oSENGv6mybY6gTK7SoIQS0WZGvcq34Q/jcv6bCmErMU2TrwvoQF6v2/mbaDkPpeg5ybSQvVOJdGh7xUf7KhL3lUSkVVRk=,iv:Mvzu28ETguqZDNWyocAFVmfoQ614m8hDUkSGRVw7Og0=,tag:Z/CiaHrSsiEjjzMfnC1X4g==,type:str]
    version: 3.13.0
