apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:N6VnQ7iLGCdgnlPrZPIlI/fRlDAuZv5g0tzIxF0b0PwoS3NbGx4QBsZ5ASwXY3Xz5gq5haVb0UO/GNplmIhsJ01+jJ9bz/ThUU0s2ZxG3SNv/wvStdF6Ogha31tHTCR8V5OMxF2jHOYwTUdCdLcIkBld30ikgv1i28WwOHvvBkY+EG9SNHdSjhMA8UNNltHkNouAMBLjn5LULN6vuezUgMgrGqIawMP1+teNKNIH+yz3XAtN7aYoyQ==,iv:14MDDEbeqBOCTR9tixn46PpV+GHuRAPawZRzALS5jJ8=,tag:WInPa/s4NZN4j+2BacAExQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSmg4TkFWWXV0VStQdzdq
            a1ovQ0hpTFNhNmpjRzFwRmx2ZE9jcHpVbEVZCkZJMTE0UllsVjZGa0ZiUXJ6L05Y
            TlRTcGhNK094ajdDS2NFSU1YR1pGeDQKLS0tIEwrU29ySFpDYjYyeTNWNjFuZ09y
            aHJVWUhoWnRuSDZBZGFLNGJhSUM1RUEKK8hikc01jedeNBc8njqvZ6ae4QFeThAQ
            THhMj7yEObNBKGy9AJ+6u9+ZliXolalhVUPn/nKI1ugX6YLlJz2vOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T14:34:25Z"
    mac: ENC[AES256_GCM,data:KboHaIcY3mIn4DQJeUttaDHsgpSrhRPtaFsfA17HJDxwJFuQLO8lTuOQQ6H0kvg6PQT5r7ykyAt0TYo/hWUZSSHhniHw30gukIBuMBBoRuJ4OFtVImov0vxgzWfWnDoneutCdtLVs/0T/FE7g8sSTh1F9eZtLOsL6bpCbQiWcrk=,iv:dRO3X0vMrClXcnT7gXhnFRctK89iLHeCURTA++eIsKI=,tag:Lg1xhfaWzSGGNYx1/cpDtw==,type:str]
    version: 3.13.0
