apiVersion: v1
kind: Secret
metadata:
    name: github-mirror-token
    namespace: backups
type: Opaque
stringData:
    #ENC[AES256_GCM,data:7xxKzIQLPz/44L3hSXa8GLszhd9SekExyyTMkY0vkxmjxZUVH/A9QfULGoNMJDEYWum7s1uKcHjLyNU5yv3HiFqRg2xVa4BacveD2OM=,iv:v3eGnz/7CVi4FzVWqLy2aF80plq9WKdfV1grOlxD+gk=,tag:jP+0nF3QfVTDxAZwjxrjpQ==,type:comment]
    #ENC[AES256_GCM,data:8ed603L6LN3ax+tijQLHPR+T0ZFQkHbAq6GF2RLINnA1EKuh+2fxwwVLGyjQY8mNN6wp+buOi/M+d6qQp6TWt72K4C9ilC0boore6Q==,iv:V0ceIjLxJ9+WXMB9H9tiwROT4fanXLvOtDVk3lB9lSk=,tag:6IHK1RHkq84jHvESAVpXyg==,type:comment]
    #ENC[AES256_GCM,data:p4wkGpjkEp6PK79UwuoieeOQN5Hz6TEswbxPRoRa2bhCcMqv42sngQ==,iv:/22oQzMO845O2TN4Mg8B7nbNeAjxVoO20PByNoj/UM8=,tag:exCS0lgJ3zSrUPG4ufZX0w==,type:comment]
    token: ENC[AES256_GCM,data:M570CxgeIR0DzsQrI4y4pxuudyU3edtfBEMjqR4C78y01aus1adZp5I3nwKox4ctUBXeSS2X91rjVNG6VNkhdLyn/0TMdB3lNFEKRIDbph8FLiZVCljWs82AIKv/,iv:Fo/dGoYBQxMTxETXD9KYQsGLCeF8bc3KeaM578oMVuk=,tag:8k0MTQ/NvZGeE4+7+l/DhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4S0ZBUlk4V2xlcTl6UmpL
            UEtNSXJpaXpyclh2ekdsMVJmaUpqcmNiTGhJCngvcG1EeC9pWHRwT1FpbXhNZ3c3
            alZtMmRORUpwcDFyTzhMazN3Q0pDVTgKLS0tIGg4L0lBMTR6NExtOUNpaTlPQ3kz
            RWhaZlZrMEpIbFRmQktiZURqdk96bzgK5Gz5MlN/tslIR1PKRCTtVPhV1uL0Gi8U
            zIGDHAnMbe57t6C3ZTJxJ/To/vMn/qBepZ8N29/U1ehRTEcUxiftDQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDS01weWdvYlVGR2NENDVZ
            YWI1c09PUTlUcndIdzN2RE5uVnoxbHk0eURVCkxqUFU1TGtVd0xFT0hiaU9ZZFRP
            T0p5empOVHN2Wm4zOVpGbUgvZTcyR1kKLS0tIHFwaWRWdVNqQ0dHOU15bDMxdzdO
            SHY2QXo3WHB5ZjdOQlVpNkVsR1hHK0kKp+ej7JJV3+HA9vN9KxMIhqvgzEaUr+AN
            NEOEecnf9GN90ZR7YP8LFq2MizkZq0bLsF4MUGjdS1grkgJ7bWamSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-07T01:10:16Z"
    mac: ENC[AES256_GCM,data:3+IqJucaGBOdvLUI/SrGtHRTozVYvpSiMMQ7AmKltXRUQe62OJhpX9hNdqVMLfteF2Xjv3+bqmZhi4Qb6o+UNx33HIkkH0j6xMkMrXsrER0OFWVyy8p9nTOOtugh9iwQ2ZQDdU9QWuCP2Nw9je1LHnoz9BPk95C5NtMROL5JCw8=,iv:HtqrkPERNNE6myKP3YEMtWKJ7Vn27vrVUiVVV9JYM8Y=,tag:3zou0msCdMyepfRl96U8Xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
