apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backups

# Defines the backups namespace (shared with shares and kopia)
# This component is always deployed, so it owns the namespace definition

resources:
  - namespace.yaml
  - cronjob-email-summary.yaml

configMapGenerator:
  - name: aws-s3-sync-email
    envs:
      - email.env

generatorOptions:
  disableNameSuffixHash: true
