# GitHub Actions Runner Secret
# This file should be encrypted with SOPS before committing
#
# Create a GitHub PAT at: https://github.com/settings/tokens
# Required scopes: repo (full control)
#
# To encrypt: sops -e -i secret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: github-actions-runner-config
    namespace: github-actions-runner
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:ctPoWZixEo/UPFGYAmKdQVEJd2eJlAnUZLWDXbCxTMasPT++DpdW+QAgxX/mR9I1IENjy2T3jtUWI5NI2L5dFm76gUKtHxui9UIljyScflEhMspqtNAknCUPXqvnbK0U9z8KJDUX5ucvr9Xt1NXxgixMC4zpvU1rXOpZvOUzZV1Z9tuY,iv:TJfy8bnsl+u2eNA9dDngxab1PN51M64Xa1T2tAYtPLs=,tag:p3ea9gG4MpFSrc+Jv5CmKg==,type:str]
sops:
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrV0dvbURCeGQzSHdZNStw
            MllFTGg5SjNObzh1VnBLUk1wOWZma25TMkRNCnE4UUpFWmNlLzRKWVRVTG83WS9X
            ZSt4TUZKTjVGL0g5R2gyUmQ0dlhvbXMKLS0tIHdIdG44ZkNOK2d5bjF4SlhXMnhX
            c0NrZkZDcDhPcFRGYk42Vmh4d0V2bjgKIBxHinA51dM+7WteVL4s/PUQdQw8r8Gx
            7cb0D1aNKm0P7QrsG8A0vUKLqFbHYPUczn5Enx/59Rqgg7uBrBWxXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T02:52:41Z"
    mac: ENC[AES256_GCM,data:w/sfdaCOKRUqI66ApjOqUHYjKFyOIFrmHRMx4vA6WeOAnLYgVX/KDCLNVzKondvox3Kp5zAozK2dGuBI/ZH4WDJShdRoh15PXxXhMYrVkapehgrATd+yq3KG8+sXx5Luc5DW0pBuXue2uurgUbr8BE6yIcqITtwSFY7rxF2PgiA=,iv:9hFh941j/6P8rSdH8jg1yWIgqRJy0Zi/m6RAtAvY80A=,tag:V4cnk1ElekM7Bny4jWyN2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
