#ENC[AES256_GCM,data:onJaz1vLN8/HRkTJjN+6wGcDsQROcjO0vs3S4nG9e0PP7kuos379,iv:Wz5AAZ3fae0L3/DW+FgOQrhvKhYsWRbTMq/SbLKSxUU=,tag:ExiLohq9DXUgXIJP4pJOQw==,type:comment]
#ENC[AES256_GCM,data:sLHQbX0hCNTEgbYScRqXJKJbUa/ebPL21zEwgtqXqfR9MotsY3gEsxslNCkrFsdnWx17PlAmhlURJZ6wILV8nSL8H8XsVgF9uoEe8bV+b/Q=,iv:UmVG2SK02+sjJjX3HiXq+rfG/VMgqcFbD09cfOoGkxY=,tag:HlZ2+QjCYdjMY3HG4w7Y0g==,type:comment]
ha_access_token: ENC[AES256_GCM,data:qpmr/uvr6cWq815anGRKgCg5f/CJ6j5ZegVAqpBivOPh6nU0B7N7k2FddmHO9ykckbyA+6p6gD8O2YxqWeehFUF+OOpQL52xcj1GL0sVZb8rcByRd+2Eis0zvlL+J6MR/9hVrxYeOJP/wbuUE2CSgVOVszFN+H+v5iWy8+NBrBXXNrrH/30CzFSR2M+0eBWEcoaTo99Rc3o7nTLhk2Xs7lw/b3UMCKDIaMHA2DFGWumKcrmepaYd,iv:eXgyB7S8aI4q0GvllR9cv0c0USbkL/AmsPa0Q8ArKaE=,tag:HKWUlbigXLlnq1LCB2FAGg==,type:str]
sops:
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQ3BaWFpQVVl6TjI2U1lY
            VE5SakZkc3lUbWRIQWp6WXJsTnM5SXVsNGxvCi9SbEZ3WU5ZY3lOR1NDSkZ4VFRy
            MkwzWWIwSEtPd3BQbFNVUTYyUVpnbWcKLS0tIFlTRTF0NzNidjlPbzJEMDhTZjdB
            TVRuL0JTK3RzdGY4M1p5VjF3RlhhRzgKSKjKXpB47cUap2nFRzk2+KnXRr3s3JFI
            2qoA8pqAiS7SCbgQwPEOW17ZLwWaAJVlj41OGnZS3iQVOe2uK7R3bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T15:35:09Z"
    mac: ENC[AES256_GCM,data:uuOoFtuGBx123MmbGGLiMNJy24z7dyNWZEaYjfQE4gwfc2KizDJOZGJMGleC7n+IKIsxUgOOLi9D5amKER7UTk08MdqNAe9pN4BXnb7zQglYIFDu6gAwUA5xOT5xsdOPQT9k/sz7z/fZaFyI+uWS3yaYppBiKH83o9+YgA3kgEs=,iv:mOqGq9exAbRcHz7ISpt0EKR/NQAKs5/8KyOi4o1LSPM=,tag:oMfY0BBqibRtPotTT7CNVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
