#ENC[AES256_GCM,data:onJaz1vLN8/HRkTJjN+6wGcDsQROcjO0vs3S4nG9e0PP7kuos379,iv:Wz5AAZ3fae0L3/DW+FgOQrhvKhYsWRbTMq/SbLKSxUU=,tag:ExiLohq9DXUgXIJP4pJOQw==,type:comment]
#ENC[AES256_GCM,data:sLHQbX0hCNTEgbYScRqXJKJbUa/ebPL21zEwgtqXqfR9MotsY3gEsxslNCkrFsdnWx17PlAmhlURJZ6wILV8nSL8H8XsVgF9uoEe8bV+b/Q=,iv:UmVG2SK02+sjJjX3HiXq+rfG/VMgqcFbD09cfOoGkxY=,tag:HlZ2+QjCYdjMY3HG4w7Y0g==,type:comment]
ha_access_token: ENC[AES256_GCM,data:qpmr/uvr6cWq815anGRKgCg5f/CJ6j5ZegVAqpBivOPh6nU0B7N7k2FddmHO9ykckbyA+6p6gD8O2YxqWeehFUF+OOpQL52xcj1GL0sVZb8rcByRd+2Eis0zvlL+J6MR/9hVrxYeOJP/wbuUE2CSgVOVszFN+H+v5iWy8+NBrBXXNrrH/30CzFSR2M+0eBWEcoaTo99Rc3o7nTLhk2Xs7lw/b3UMCKDIaMHA2DFGWumKcrmepaYd,iv:eXgyB7S8aI4q0GvllR9cv0c0USbkL/AmsPa0Q8ArKaE=,tag:HKWUlbigXLlnq1LCB2FAGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJT0lRZnYyT3R0c0kyYU1K
            MW9QWWxJVFRHQk1xdUQyV3Q0eStFZlRtL21FCm5RNWVOZnoyclJoRHVMcDJ4SEpS
            YmxyejhmQmtWWUlJQnEySDEzci9PSEkKLS0tIHNlMmdoa0ZDbERiM0JveGVWR050
            YlFBQzVuZDJSVFNxMldINlFGOVI2Z2MKbFgDNh2DSt5qqe1oZNK6tMMe7xKdw3TS
            Jm9aBnROUCyTf/TeVQnA13KeU329NdNRiC5WqPmqrlNvfoSw80o9oA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OXh2R2s1Y1pxbkxGSTQw
            RHRRZlB5dkh0aWRLMzJLNDBPQ0haaFI1QjBVClk3d1BIMU1DR3YyUTN3eGVPYnFm
            TGErZ0lUOUJTcGZUMjBLMHV5RXM3ZmcKLS0tIFZxUlBvT0lOYVZlSFZTVHRPdVVv
            b1dRRVFiOFBjUGUweEIyQ2NYUnZTVFkKv46z6aGU8OSa+V5IcYCViUfTIELxR1tI
            QqOBLO5sF5WjxQv6EHUs+dO/Da3tu3V66L/S20yRYoL71cChcBhenQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    lastmodified: "2026-05-08T15:35:09Z"
    mac: ENC[AES256_GCM,data:uuOoFtuGBx123MmbGGLiMNJy24z7dyNWZEaYjfQE4gwfc2KizDJOZGJMGleC7n+IKIsxUgOOLi9D5amKER7UTk08MdqNAe9pN4BXnb7zQglYIFDu6gAwUA5xOT5xsdOPQT9k/sz7z/fZaFyI+uWS3yaYppBiKH83o9+YgA3kgEs=,iv:mOqGq9exAbRcHz7ISpt0EKR/NQAKs5/8KyOi4o1LSPM=,tag:oMfY0BBqibRtPotTT7CNVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
