apiVersion: v1
kind: Secret
metadata:
    name: ai-advisor-anthropic-key
    namespace: auto-remediation
type: Opaque
stringData:
    api_key: ENC[AES256_GCM,data:uDHkjpeGHkf9pxc//l45e0ZMqMfR,iv:L0mPuDKTbq3N+ZYeTMP1TP3k9S0PxSdgoumhzhwvoZE=,tag:GGdtNpWe/4ohvCGJXO/l3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdzlVeGdtZmZmSG96b2hM
            aWpUV1c5bC9NbEJMNEZBTEo0aEJrMXNRMTBNCi9KSlZXL0xEcm5VRzdrU1ZwQUcr
            N1hRWjNnM0huajVQdkc1ZWNkbGpkTjAKLS0tIHJmaHRBdXdTM3BxVnBaZUJDaTF4
            RHFUMVhtcnJpb0RnMEZkVi83dzgycEEKWYn7n4uPC+gi8AR4Z4d938G2SxZIWh6E
            gNq7JmADoo4/0U2RHyAhUcUfsrO+FT1JoghZfouPT0tfcHzghK3glQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T18:16:36Z"
    mac: ENC[AES256_GCM,data:87lG2nSzmazm9ptHVAsHJ10V9oo1u1u5RNan7r4dhs4ftre7ysViwfaSqow1OLci7wtI/439ouOtAUpmNidjKGv9dmzTFHFDaxMH09tOvwVzOGUCZt0sEqBKD5+CUnX8+bJ1ljOMDsz3NlFYGwCYlGspbAD87um/cUp3UCjpZec=,iv:BbHbKwNZqWvddXN1ktlPX1STFrQo88n0kVPgQF4U9Fw=,tag:j0/eIeQQ4cTfHg+7OzJ04g==,type:str]
    version: 3.13.0
