apiVersion: v1
kind: Secret
metadata:
    name: ai-advisor-anthropic-key
    namespace: auto-remediation
type: Opaque
stringData:
    api_key: ENC[AES256_GCM,data:MhOdXkFLgAW6A5C+m+TNYNC7bt23afzqm7PJGPKTh99pifVeCrS9XwyvNuZIrVA2kQTf3tI52bo23STDxmJunL0WHzjFSPagQ7IxNuS3OFpqcR/u4dGrkcGA7qIrVCSovLcljMBPOWKFI9Iv,iv:7Btv42N8n1JXzPtRM1GUATL599uMd33LfBqkvk3w8jw=,tag:falAAfCyI8QEiO/asqAq0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdzlVeGdtZmZmSG96b2hM
            aWpUV1c5bC9NbEJMNEZBTEo0aEJrMXNRMTBNCi9KSlZXL0xEcm5VRzdrU1ZwQUcr
            N1hRWjNnM0huajVQdkc1ZWNkbGpkTjAKLS0tIHJmaHRBdXdTM3BxVnBaZUJDaTF4
            RHFUMVhtcnJpb0RnMEZkVi83dzgycEEKWYn7n4uPC+gi8AR4Z4d938G2SxZIWh6E
            gNq7JmADoo4/0U2RHyAhUcUfsrO+FT1JoghZfouPT0tfcHzghK3glQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T20:51:41Z"
    mac: ENC[AES256_GCM,data:ZqmjhI3npa4FOJUKKKKZ04fom0sb2Ewk3en+UewnLTefDsvJQBb0OpT9GkTBRGS+R6G7yD1y/6LeU7IUeq/0xJHIfPMRSueReFwOjIu1RF3leJiBw5DOVT7eBfF3a7FaO8f7xaGMDSje0j0vUHs99s2Ee+NWFiOJ8OT8QQI7hhM=,iv:JI5VR9eT0IlKrDPC34y0nS1qB+knmQrh4nTINutPLUM=,tag:noo9OT7piM/hyKWH9eq+sg==,type:str]
    version: 3.13.0
