apiVersion: v1
kind: Secret
metadata:
    name: ai-advisor-anthropic-key
    namespace: auto-remediation
type: Opaque
stringData:
    api_key: ENC[AES256_GCM,data:ZO0Lu/7V4JgkPU2DOheFiN1E664uNNQJQHfMxlm/mMOs0VFWbPT72fOVFFkxl7RnJ/AdfZY7Qry4dsVM6Hp8pUGmCt4dqgA4wi1wXh/G2DPDVCeM3XMp7OSOGBecVupbZZ/RmRm3711EAwkR,iv:/vCaAhRgzbZ3xiRJEW2gHmCV/EI6P1D/w7YO7dNQ4pc=,tag:0VvRAiNsB5vVHlqt3DrrRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdzlVeGdtZmZmSG96b2hM
            aWpUV1c5bC9NbEJMNEZBTEo0aEJrMXNRMTBNCi9KSlZXL0xEcm5VRzdrU1ZwQUcr
            N1hRWjNnM0huajVQdkc1ZWNkbGpkTjAKLS0tIHJmaHRBdXdTM3BxVnBaZUJDaTF4
            RHFUMVhtcnJpb0RnMEZkVi83dzgycEEKWYn7n4uPC+gi8AR4Z4d938G2SxZIWh6E
            gNq7JmADoo4/0U2RHyAhUcUfsrO+FT1JoghZfouPT0tfcHzghK3glQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T20:56:53Z"
    mac: ENC[AES256_GCM,data:3gJ7lOWwwMgTGKbUbvbyNYSQqQEU/FF26vEGMIt6gZwAtxgiqQEtf7eQWXRITlldxMoAYRLrEsbZrH2jNDlTPVo0zeOZQRRU8N5Kg5SfEE38a+vSCjNiEwJqdPDiUHAKcI1SvYNdQxhrV3RWOdPorUEn38CJ8Abzyl7dRlOxyPA=,iv:kiD0Ra6S7ia5Lv7bHf2k0mx5mGDDDHDVpSPnwx7sYHs=,tag:uqsfC48N3y9VerQDolT2wA==,type:str]
    version: 3.13.0
