apiVersion: v1
kind: Secret
metadata:
    name: ai-advisor-approval-hmac
    namespace: auto-remediation
type: Opaque
stringData:
    #ENC[AES256_GCM,data:1W/UD8D4iMFm04qshmYIvTHQVklvSmqG46iZnUqPXudCIQa1QUt23HtBoC++chyIadiI6dEYIUxctEoj,iv:pRq8PDSnrU9OpxCmj6C2zX1yBpWSulRiLIb77THnoqM=,tag:18t251GX+StvFfxHXIHyNQ==,type:comment]
    #ENC[AES256_GCM,data:Yh6jOhANYz1v8d+kh1WM2eumQEpWco5Wg4BIu5Q6Rlo8PvlOZBfJw9D83NmDKhto8Hn+J2ynxmOGCIVTgWJ66g==,iv:Tn+ZWWbhamyUbStb1u0taQEFJIdRS6XL+VYCxzzw2dI=,tag:3vK4lzhGZ8JjxPQkti3Ufg==,type:comment]
    #ENC[AES256_GCM,data:RbFwqyQjG5M76YGXbUbQkRk3L91NY2YMDIzDUNuhmS9RfXu882cHGDBJKM5HcrBVKDuKWcqOO0YTmRsh,iv:A/VrSBSSRO1JtqzKIXIoQyyjDn35NX7tfSx5BjYuMjI=,tag:t2fuk0BV2o0v9pVWIkhFjw==,type:comment]
    #ENC[AES256_GCM,data:9be4Ybpi+CSv3Lwfl4EOk0fCo/HDnPPy81w+ndC65+fJtFaBcynxX43fPsnQ5Ta1X9ibEUcb9904fv0=,iv:fen6REeMR6yQsXDQCm6m4mTmX5OA13w8h2GB8mvWTaM=,tag:GMdkcyuG87x7m1S26Ph9MQ==,type:comment]
    hmac_key: ENC[AES256_GCM,data:K7g3PrmQnejPn2TzQt4kKSmI+on5/MOxgsVbpUDB9m8i5/RJXJMe83XP8As=,iv:zdPlG3nND+Z+E7ftq1Az/Kn8eSRZ6eG8gIDfezhN1NU=,tag:o1HZw1ZLVf8JebiDDk+50g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNWk1bGNvdHpCc2pDK3Bv
            dGl4NTVPVWFZN1YxZ2JTekUrdk5abHpQL0UwCkhwalBQYUlNN2RJZmh0cm5OaHVS
            YTNJTU80YUE2cHQ1OWdsT0ZORkFpL28KLS0tIDZUMXhiTHBNY3BLZ1ZUcnhsdkhW
            ekVuc1hPZ0twWTE1aURIMjd1c2FDNEkKzaMMCv7uz3idI2eZmgIbtKUKUcuai0B3
            Wyk5mVr2s6heOubjK5jymrWyqL30k85xFbtWeLjEzN2quYaPZ/Dubg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T14:31:43Z"
    mac: ENC[AES256_GCM,data:51td/DxubXVbJcGmqF4/CY1A6FtGLrh+EhMlz9NGIoqxegY1LH9DJyDocnkp2goi901GFrFgF8FOcPsc+K4chLBuAwksc14pAflFnHKalKpJjApn+041+leHE2omr8cp0DgnQSmcHfyCi4/dLVS2j/hXxbrDXlTITEUuUiNFr9U=,iv:3+abB1egXqq8SPwy5+fRbajRvca+sZ6j7UDLtEewbi4=,tag:rO/KXExwpAUVvnneS2+Q4A==,type:str]
    version: 3.13.0
