apiVersion: v1
kind: Secret
metadata:
    name: ai-advisor-aws-cloudwatch
    namespace: auto-remediation
type: Opaque
stringData:
    #ENC[AES256_GCM,data:qSul1QuUmFT3JlQkrtPj++5P7NPHUBa4+PnjGL6gxyTt8OfRmBU9Vfq4HhYZ58D6565fP6GrcC0ceEogtVA52an+uw==,iv:AaO0C6N+FARzoCek3MH1PQjPctbvVawekjS8/AJlIho=,tag:1m9P9E0SxP/kMN4Jpe7v/Q==,type:comment]
    #ENC[AES256_GCM,data:MdpkKem9Osy4f4S4AyxzAjasvOkJ0TnJAG56GEFVO43VUEleWUHQXrsyyT/HV1xUFZOGr7pHFDDOwuDhBHLiBGE=,iv:Dv7q+lCfu29XszfwEoWPkVj3mNcrwYqeGuRRZFclJ24=,tag:vLlxBm/VvVvdDUmWrjbJIA==,type:comment]
    #ENC[AES256_GCM,data:wcCsiexHFmKeU8AJqaG1Zg1Ln6r/7/ut9zKTffNayteIC3wDgt3Dtji+Th2r2RwC2T3f3+7XDUAyaZI6lg9+yTdL+yQxEQ==,iv:g3WjNr2uowCE6eAHuSR7OjP02Y6ToIxHfJZ1h6ibnoo=,tag:6pRvaZiUuuYAbb5M98P0Hw==,type:comment]
    #ENC[AES256_GCM,data:+ombuWJuj8lFyD8rRzUKda0aV7aLIfXfk4pLdRUbgGQCT3o=,iv:xkCpLU5auwY33MkRz7ZliTtJitx3X0ldvUkhO2v/NU4=,tag:BERMR4Fv8U8R9nKwtdeq2A==,type:comment]
    #ENC[AES256_GCM,data:icppBzKp+5riZS7rb5kbN3g2obhbxAbGCXZKMhrLyQy9ryj4U5A=,iv:2VfFZCvGPaqU15ius+alSzBo6nFJC+62PM7y/fO0UwA=,tag:CE6zoVSURXkkIQrcfIygbA==,type:comment]
    #ENC[AES256_GCM,data:Gz1KxcEZt8upS+RKa6jhnGagMLVg8tDTU6vyx4lZspKKsLzmDrfZAsQx,iv:VR7nmaQKbI7vo3Ub1/odhx0YFBpmrVwdlwTjfGkw0ME=,tag:Kv6jeuGaS0T86gquuFGc0w==,type:comment]
    #ENC[AES256_GCM,data:hck9LG+KeemIbTXQileWk8j0voZso1/MuEyb1V0zCTTcUFm7DndXEWIX5op3Q9F6XTU=,iv:bwJ+hxa0jJ/fWZfPWk+PKw2oCNS+m8QwG5969LTGEs4=,tag:oGq5zjL4xegxHh5vBQXndA==,type:comment]
    aws_access_key_id: ENC[AES256_GCM,data:oSMUZDylAA==,iv:zNlTTBPhYRlvtw4/a9LTIsq5L2Ptyviy1q+kZjTTCcE=,tag:PtQiH7wDQ38yFY8DxpImYA==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:IwdQqk4RGQ==,iv:iOwJ08trxkzJlrvDCXapot0dFeW3obp6I54zv1gr+as=,tag:sC3iTaFHJOxLq1RBjwK6PA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQUtwRlpwOCt1V3l6ajBq
            SmVnYUxuMjFFWUEvTHFWdUtEOUt4YnUwR0ZvCnpqZlloeW1MaWVkTHJ3VWplUGVr
            OU1wNjRGR2FjN1EzVy9uQmY4dkx4NWMKLS0tIFRoTUwxa3pCM3VFR2JIUWhkK3Mr
            ZXhOSFRhZmdDVnlGNjVQM1V4aDFkSVEKqGhQBiHMDLayC6W4sDXgl+3QXOcoOmtS
            RJa4f6kaeIRdhnmUyceubClSubnlrHigOpO6McW4EczjGv9rzgiXQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T16:41:42Z"
    mac: ENC[AES256_GCM,data:xREp+APw0kqUO7JjfEO17f/iAfPJn0ppCbLitxScpewLPcnOOg6QYa4e/Ov2U2cDJj3SHNaNuJm78YneSB/OkXI+NCO6dBNt/3zUIYeTBAPubk79oGWrRrUGmoWNrBqJx+EyZhn4nkV8wlP0CpZ+9S6P1iHlefuiEEzdB3rG78s=,iv:7w3uqAWtYIsqn3OvjD9AJKXCpcQ2epKf9k71nFJ5ez8=,tag:bNZ6PP4E/eqdBxZCBMG1XA==,type:str]
    version: 3.13.0
