apiVersion: v1
kind: Secret
metadata:
    name: ai-advisor-aws-cloudwatch
    namespace: auto-remediation
type: Opaque
stringData:
    #ENC[AES256_GCM,data:qSul1QuUmFT3JlQkrtPj++5P7NPHUBa4+PnjGL6gxyTt8OfRmBU9Vfq4HhYZ58D6565fP6GrcC0ceEogtVA52an+uw==,iv:AaO0C6N+FARzoCek3MH1PQjPctbvVawekjS8/AJlIho=,tag:1m9P9E0SxP/kMN4Jpe7v/Q==,type:comment]
    #ENC[AES256_GCM,data:MdpkKem9Osy4f4S4AyxzAjasvOkJ0TnJAG56GEFVO43VUEleWUHQXrsyyT/HV1xUFZOGr7pHFDDOwuDhBHLiBGE=,iv:Dv7q+lCfu29XszfwEoWPkVj3mNcrwYqeGuRRZFclJ24=,tag:vLlxBm/VvVvdDUmWrjbJIA==,type:comment]
    #ENC[AES256_GCM,data:wcCsiexHFmKeU8AJqaG1Zg1Ln6r/7/ut9zKTffNayteIC3wDgt3Dtji+Th2r2RwC2T3f3+7XDUAyaZI6lg9+yTdL+yQxEQ==,iv:g3WjNr2uowCE6eAHuSR7OjP02Y6ToIxHfJZ1h6ibnoo=,tag:6pRvaZiUuuYAbb5M98P0Hw==,type:comment]
    #ENC[AES256_GCM,data:+ombuWJuj8lFyD8rRzUKda0aV7aLIfXfk4pLdRUbgGQCT3o=,iv:xkCpLU5auwY33MkRz7ZliTtJitx3X0ldvUkhO2v/NU4=,tag:BERMR4Fv8U8R9nKwtdeq2A==,type:comment]
    #ENC[AES256_GCM,data:icppBzKp+5riZS7rb5kbN3g2obhbxAbGCXZKMhrLyQy9ryj4U5A=,iv:2VfFZCvGPaqU15ius+alSzBo6nFJC+62PM7y/fO0UwA=,tag:CE6zoVSURXkkIQrcfIygbA==,type:comment]
    #ENC[AES256_GCM,data:Gz1KxcEZt8upS+RKa6jhnGagMLVg8tDTU6vyx4lZspKKsLzmDrfZAsQx,iv:VR7nmaQKbI7vo3Ub1/odhx0YFBpmrVwdlwTjfGkw0ME=,tag:Kv6jeuGaS0T86gquuFGc0w==,type:comment]
    #ENC[AES256_GCM,data:hck9LG+KeemIbTXQileWk8j0voZso1/MuEyb1V0zCTTcUFm7DndXEWIX5op3Q9F6XTU=,iv:bwJ+hxa0jJ/fWZfPWk+PKw2oCNS+m8QwG5969LTGEs4=,tag:oGq5zjL4xegxHh5vBQXndA==,type:comment]
    aws_access_key_id: ENC[AES256_GCM,data:OJtaxDORWkQfTSYHB4s0zhWRQ5gmpAY/wcOMEofaiaq2jkXT,iv:dCOAA5t4dv1wT1FkHQV+22y45sgCJBfBrr99u2gVTkk=,tag:Dr/BSVjtoLxg5w5SrhyHeQ==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:2cyGZ/I+YF4f+6/vsO40HIQRTu8ck1In,iv:VYb9jFumxN3ou1C7Kfuz9jWcyMppvW1h6YLYJL/DKYc=,tag:ilZIVjthbhiiU/r8SZMa7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQUtwRlpwOCt1V3l6ajBq
            SmVnYUxuMjFFWUEvTHFWdUtEOUt4YnUwR0ZvCnpqZlloeW1MaWVkTHJ3VWplUGVr
            OU1wNjRGR2FjN1EzVy9uQmY4dkx4NWMKLS0tIFRoTUwxa3pCM3VFR2JIUWhkK3Mr
            ZXhOSFRhZmdDVnlGNjVQM1V4aDFkSVEKqGhQBiHMDLayC6W4sDXgl+3QXOcoOmtS
            RJa4f6kaeIRdhnmUyceubClSubnlrHigOpO6McW4EczjGv9rzgiXQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T16:54:49Z"
    mac: ENC[AES256_GCM,data:U5eqvCSMLkef7tPIrS4vN9fWT1IoNE8as7v1y0NxgA0194wBjuxTfV/RJRpoRfSX9Mxl2ZeSdqQ+3So89k6C2TMsuRzg8x4PlUCzM2fFQe+BvU+6NHd1+KjbKS5wHTfwhVExfq9jKwutQCu1lWSfXfDt6YKIptuE+w1dJ8lvMfo=,iv:01BbOPwL46jZqc5IJfqf6wJBdnuNjtQJxp9NDMdknPI=,tag:pnFzWa9W7Epchxs4tbGwqg==,type:str]
    version: 3.13.0
