apiVersion: v1
kind: Secret
metadata:
    name: ai-advisor-smtp
    namespace: auto-remediation
type: Opaque
stringData:
    #ENC[AES256_GCM,data:UxvNc6X2d3pQqzDYq7OFfLxnnzta8+5Rdd+TZxK8mGbhjF6lQ70OPgsr2UPeHSU5OFDagiz/ApBG7P440wRDudY6,iv:NLo9HmsKoBZG4NjEYaWOank73qcMl2T1Q2dwBJFY0qs=,tag:vvpDuTiKPMlZHc3xipZmiA==,type:comment]
    #ENC[AES256_GCM,data:i41KhD+Y3LV0G4CTS/HcEmtcdTULT7Srs1MVDBFXd/95UoiFYeXajvfllPU9eKpUzdkPCF+OxrDuxYBZCdyG,iv:X8lMzy+PXI76B+OEQ5aiwsz+yXttwTs8l/JJQ0CdMIs=,tag:MQ32ZRz1eFSG3NsX97qwaQ==,type:comment]
    #ENC[AES256_GCM,data:OAW9eZXw7eOQpTxHdaXcfl5PfodaKt/CSlt5JS3FfdrDKtQocgdpsLpTMj/V02/mIwupyksC+m+fnKz+lRTMhQs=,iv:Wx0PY5YpqOqalDrfOxAzmEHHT1ioOmdU9vYr3avBSGw=,tag:oRJzu5E+PBY8ABzeAsFWFQ==,type:comment]
    #ENC[AES256_GCM,data:LseYXQGIR6CLv9r+Ce0YvDV+WWjV67mb,iv:e0cvrQiCF6gb0hNtSd41cPK63CSzE3kf5+6miN9MWYU=,tag:yz0qDUmp6paPu3VVb5poMw==,type:comment]
    #ENC[AES256_GCM,data:i82h9MzF0Xdo2LYgVGFImKOqpaGC/VP1rihj3z4dt3nH6qv19c5Kou91DVmT87ZwPi+mVwKzLmz3bEXP70XriycyS5WqjIY=,iv:j/u7o5X7SoW/BnDe9Qw4zN6RQRO2VQ6hOHwGGF4cezw=,tag:VXj4Ul3sLIUGZSCscVC1dw==,type:comment]
    #ENC[AES256_GCM,data:quH8IN16agUzmxfcYDF+zC4plFQEb/9IqwQdpEUyWmTBFXtT1z8lwXE=,iv:rBCIbHzs5qNV2qVukIpSJoFVN0oX4JuDtq/x+EA6A90=,tag:9suasDNB9qbonw4LCVcDDQ==,type:comment]
    #ENC[AES256_GCM,data:BgQ3cE6PwMsCXLt9uyJ2RVTxi6oT6FTGS//DQWAS9lcBCrRl/ZOnI37d/W4AeaQZ8AcM0ThatToP8m1oLm0i,iv:6bz9kQBthRz76/3XN7aIwvdvyVdEtY7eZREe2wZbjds=,tag:zem4NphCkrj3OPOHOoFtpw==,type:comment]
    #ENC[AES256_GCM,data:CFXCEXzhtl3OBt8QPX/QL2o67qSeH1xwvWfr7GCRuA43Nr+AZ0pX5YWIYRsqVK0VmorSZ6zTT7YYLuUxcVQ=,iv:Su4ANREpIWyUMTDuItVPVxQnl1p9CxeTQmLJKAKQU0c=,tag:+7R7yMzJrCdbek2fdvqPEw==,type:comment]
    #ENC[AES256_GCM,data:GjFs8tyjqOM/EUGZVBJQ9/RtNAPjFYw1OCBnS2gure0t+7YoFJh61ddvF9sTp10NFOyvJ79flGqagtw=,iv:O3kBo0kgE/zD9JJRrzwMViZXOMv6E9BfWlXhODDOMSQ=,tag:4m3S+VxGxy6+1A2V8CUPpA==,type:comment]
    smtp_auth_username: ENC[AES256_GCM,data:XUXZgAaiuVqCJKmUZoBltSQ88rI=,iv:tpWNK4XO33YWN13LDGbjc4KCXaZgHjCA+bcqhK2OcAk=,tag:Yinukq2HxwfwV+y5AJUEUg==,type:str]
    smtp_auth_password: ENC[AES256_GCM,data:4v/jknOLsGbIXWRL1N8pR7LVqQ4B+LcErMhnkJneIS6e4XufVke+3CijeDY=,iv:zbmcsJZyOgcBELF+MNt/OXQVzkX2dzXDL0CQHvN30sk=,tag:rMSMsIA8tg+x2nGnXIXg+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSak4rbytrOGh2aytMb0hn
            YmNxVDgxeCtJZzdrRTk3dnpsamYyRTJyS0ZJCmltSnpTc0J3VElSVlJWazJNa1J3
            V0pZYzYwY1I1dWpJLzYzc2grUURNYXcKLS0tIE1Yd2U5UHlJQ2hNODBmS3ZURnBN
            cHJUSzdHdUVKSjVnVGowb1JkejUwQjQKpmHr6ajFUoNQt+ZMu3A66OdAxFlcm5Sd
            gQ3R3+PezDAYNVyVXfZVXa0Y7ocsHALUkg7I7hUmssqjvRbrAwbmRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQU4vY0xOTmNhWkNQejZ1
            amVRZ1dpQ1ZqenZCem5WZU50L1pYV2daVUZjCkFrSmFJMzlibDlRam5UL2JnUXY3
            b3RvbmtCS1VreGxWb2J1bjBwR1dqQ1EKLS0tIElsNzlRSFMvRVlRNVkvVmoySnQv
            OWZyYmx6WVhmM3NPeDRLWnkrb0FqblUKPBSFVro1DdEy91Rd9rYUdIcj2H14kSag
            A1WvdVwEPKhdoGv2RVDTG7ULXzIAi7CqNdQ2boGX1QAA/Ue9E0duJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T20:51:55Z"
    mac: ENC[AES256_GCM,data:+8idg7k/fNl8fmKk2YoCfTDMFbCWgDqhcTKQ4+t0DQyFM9m9b3ZWJzJncdSFlawlJ51sWlx/YwajYP/lqPnc112DFSu9aPUZA/COLE49Z96TISElIac01C80NEIoxymZysLtQzk8Scc684EV/eu1KuCyBiaKMjZMBAZMFTVLM6c=,iv:BsobiIreIykWEgul1eAGQMkv45GOilL2NOMq/rbG6rA=,tag:+5rNEk9FEVCEi3CSzDy4PA==,type:str]
    version: 3.13.0
