#ENC[AES256_GCM,data:n9vL28FI9PIqySlm6SjadF+krZhz+uRG,iv:S1sBaXupShsJ0NejQI9G7LQQTBuCW1eDfqUxfswi6pE=,tag:hsf/a/vV+aHjXGcjz23ouw==,type:comment]
#ENC[AES256_GCM,data:G+fE8VZKorO4KXADJO0g6lOA3pEreXV2+AiavDWf5SwFdcZRdY990pF7dCbKXRV2nRve,iv:DZdljXS06GEVUyL/h1tJnw0ziIbcKhem61r0znCFgbU=,tag:H/5jy/7MxHd9a5gwRX8efQ==,type:comment]
kubeadm_certificate_key: ENC[AES256_GCM,data:gOsXJIeCBF4fPXlZDDGm1InWUtKvwkPhJZ5zF+a/k6BZuvD9hKw6RD1Lqo0nNGd96ySE/f9q7YO/f4PwKF167w==,iv:5Nc0FxA9zw0TeArV6kLLXpNQSEAt1opm08dJnXuA0r4=,tag:7MSWjpUaqcU/kVTb1Kh3yw==,type:str]
sops:
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbWZieHRYV2dUUHR0QWNs
            TUszNmxrVmFucml2RmkzK3NDZUYvR3dIRFdzCm0zcGRZcGNJUGFPQ3FvOFB0TXBw
            amRScUs0QW9tbkhzazFRMm1wY1RYaEkKLS0tIG9UYjdJQkVWdFczbWJkTm1kemZW
            T2FPNnNMc25SOTRNUUkrTENsdlJkbmMKeZutspGmLWG5BIVcBmtaTwzghm7ItUkJ
            iX0rbPQkOTMrvJeygSqz2u9AsG+trUvVqqaxpw6O7YFoQ5VEYP/ZXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T15:36:50Z"
    mac: ENC[AES256_GCM,data:EPcpevO4HqHfQLi5OMp1P6R1br3e7EgsbVLMyIWJJsRfrD8Btmrl/0I2kNQnyqSojmKaExqvfDbKr4I5DupQmhZoX99m/XDsUzTaeP83LnygfjFxNJZLCr/uOnByf2+Ct6hY6D20jHFlGb9Tv464tN5caAFv4WAdDos00dUN6QA=,iv:akFJrX0R33b4G3oqo+JmRH6JTrbM7xBAHZ6eXxvojbE=,tag:gwQ9eGLSgV1mkk8XzAjCOg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
