apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home-automation
type: Opaque
stringData:
    #ENC[AES256_GCM,data:HoEjvjwtPskBRIHpptAOTyKY1mQuxesPozXNXXvkNPcBAia0,iv:O6ySvZ4ZNVzmtEahysNO7X8eMxbXm3eDM2jLSNBFmug=,tag:RHo4gvF/1T9BZDFvMPXo5Q==,type:comment]
    secrets.yaml: ENC[AES256_GCM,data:Hyl2UAqlGIckDaErXO0uvyuDa7wydNYcE84Srcg1m/EzHMpYbbB7bNe7Y1xpZ4a5zPPIlF0c/9e4eQxAjyuxhxURLDNIUwq8GiRwAK8r08zfB2x/b5RhdYQM7zw3w7cJR7pxlVx9h1Zu+lvT4TJHr4hEycOB72R+,iv:IT6IuyH1+nXQHz5zNlZmmy61pL64+snsyxIqg89aZ1A=,tag:u4nNj0a4iLFc1VWVlk2yJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZkFwRWYvM3FkMXBvOGxh
            NXpDRkRSRXh4SFVEUUN5Ulh6K0xzZ3Z3NDM0CjVQaGZYTnNLVktjbnNrbWhPZ01v
            TUhDV0J3QzZ3eVFrVnMwUkdJYWg0aEEKLS0tIFhDclU5eUw3OC83QmE5eEtRM0c5
            MlE5d1cvK1g1d0hrQjVRMWNJZTI3ODgK8ZA6AvxZyS5WjUUCnqAyZs0ob6RrGiXi
            F602Ylcvns2TbbGzUR7vbSJLixIqiUUgFUPoZ9PnWZ7/Gh4ozkcwUA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4My9sYXRBQXVmYSs5NHRZ
            dTFFVktjQUIwM3d0VXpGTlhia3BJbnhmYURVClFFMVVJVWhpaS8wdW1OSGpPcjJ5
            QmFoN3NlYVBzMmI2WWVEdGhIVkVJbTAKLS0tIGRVTjBId1AvTFBEbnJRTEdrSVN1
            MGRQYzJ0VmhtYjBuc0hSbTRuS0RSdmsKrqmiZKzYDAs22je9YFOyHRVrP/q/H2aA
            r4v18DtQ37SefsG/Hp9cX92zn1FQidE34dggRApeXmQ7zE44R6z7Yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-06T04:50:59Z"
    mac: ENC[AES256_GCM,data:j090EOx28Z6rMGOqpajx67TcaspE5nILTurJx2H+KqUpmDKyBi/kU7a57pM20Hc7umfqCyZ0/pIaEB0paG1qSEgMsqwMhgUSATCdZRDnpEfBy/TUp1vyH851pZoliBywY7xhbMBA1rfOMBzZe74MhXbI5nTOYsR74BUWLuM1VlY=,iv:ymxbeYKh5f5CZGOvNnc5i7NI/SugG0FzE83DWqD+MAw=,tag:LVATFN5Pe4RM/fqiaGB7ag==,type:str]
    version: 3.11.0
