apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home-automation
type: Opaque
stringData:
    #ENC[AES256_GCM,data:HoEjvjwtPskBRIHpptAOTyKY1mQuxesPozXNXXvkNPcBAia0,iv:O6ySvZ4ZNVzmtEahysNO7X8eMxbXm3eDM2jLSNBFmug=,tag:RHo4gvF/1T9BZDFvMPXo5Q==,type:comment]
    secrets.yaml: ENC[AES256_GCM,data:Hyl2UAqlGIckDaErXO0uvyuDa7wydNYcE84Srcg1m/EzHMpYbbB7bNe7Y1xpZ4a5zPPIlF0c/9e4eQxAjyuxhxURLDNIUwq8GiRwAK8r08zfB2x/b5RhdYQM7zw3w7cJR7pxlVx9h1Zu+lvT4TJHr4hEycOB72R+,iv:IT6IuyH1+nXQHz5zNlZmmy61pL64+snsyxIqg89aZ1A=,tag:u4nNj0a4iLFc1VWVlk2yJw==,type:str]
sops:
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aCt2RkhsUVVpMm1pajJL
            Z2gyc09rdStGdXlydGk3OFRqUTVJUk5GQUVrCnNzOHhZS2EzOGJDMU1qM1g3RGg3
            eEtaUnY5YTA2czlON3ZHUTlFWHVta2MKLS0tIGxIOThMd1RHVzB1cGYzcWx2cjYy
            NHArWTYvc2JIdThJU3EyU3k2MXZiQVUKt2BxAloBdcv02BEm4P3lJ/GFH40PwCuG
            IihjTbKwHJhUAoOswpIAgdtkzqYDzVznYFGJB35apgeP9Nd1XR87hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T04:50:59Z"
    mac: ENC[AES256_GCM,data:j090EOx28Z6rMGOqpajx67TcaspE5nILTurJx2H+KqUpmDKyBi/kU7a57pM20Hc7umfqCyZ0/pIaEB0paG1qSEgMsqwMhgUSATCdZRDnpEfBy/TUp1vyH851pZoliBywY7xhbMBA1rfOMBzZe74MhXbI5nTOYsR74BUWLuM1VlY=,iv:ymxbeYKh5f5CZGOvNnc5i7NI/SugG0FzE83DWqD+MAw=,tag:LVATFN5Pe4RM/fqiaGB7ag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
