# WireGuard Server Keys - vpn-fallback (VM 1002; renamed from vpn-local, M128)
# Used by Ansible to deploy keys during instance provisioning
#
# Encrypt with: sops -e -i vpn-fallback.sops.yaml
# Decrypt with: sops -d vpn-fallback.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: wireguard-server-vpn-local
type: Opaque
stringData:
    #ENC[AES256_GCM,data:vS/H0b/IKyM53Sd987l01sBqosjA0XCT9ayBV0fFFNZhirTvmq1VruaOqhuGCjKd,iv:DRi/VQe+BSQEjma5kFurntLHJtSuapqkUIfe3ixao2w=,tag:RG2d4uki7qYIOWh6E7gq1A==,type:comment]
    wg0_private_key: ENC[AES256_GCM,data:lEPm7LC36VfekTFXYKZntJ73lyyy55mXebhxdU8mEwxmnn/bB+lUeOOiuQM=,iv:MlOPU9JRrG8J0MmE5x7hXZ5sPRXWrYqONwFaQ7yonbo=,tag:nbBRmHa3OoKmtR5y5iCnlQ==,type:str]
    wg0_public_key: ENC[AES256_GCM,data:pOhjKjkL2co11QdsQv8ySX1klbyjam2icf43zsZ50ioFD0uP1eWJlj5DooA=,iv:odQwRoo11CcfmIenNjStbjsf+6K2pTbJuGTFJ2zlpjo=,tag:PJITKy80I5KDnB6P3QQbow==,type:str]
    #ENC[AES256_GCM,data:yFu+VsxguP79hM64pzjjPBtU5WUESl87z3G0j8HvjHwJeBGyZFzle88824+Dyio25vIbWtD7gRFIJhCaQJ9TJuaOmw==,iv:+EIDCjn0N4HoOgKRIF5gQ0bBBgLb4iQKqP7yEXC110E=,tag:JhPGKPRGLwPBLBtmDk9PoA==,type:comment]
    wg1_private_key: ENC[AES256_GCM,data:kCYFT2HS1PI4hwZ+L2s/4fSUXlurE2Di605RnUZuC7h4eIh8/kgTVBZ086Y=,iv:fr+6TL3ilX51zM2UErEUJ9CxWTkjU2ArVNp5qwDb5Ts=,tag:82kifBpVG0hUhbr26/yUVA==,type:str]
    wg1_public_key: ENC[AES256_GCM,data:+xkgRC68ZBegdSxOr468MjiIB/DIgX7tFLhcDEkXW3EsJ02HQgat0dJ5ZjM=,iv:RhmpgYgiypysqTdpeeBa46GQ0YZ0ituUxIUz67nRric=,tag:hXO3gAkSHiMp65h5Ktg/ZQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwczFvN01acWR2cFRTQW85
            TkxzMVRvWUtlRFVWRWNPTjFzcnhqTFo5c2tRCm9zMTlNUTlONm9GK1JDUnhMR2ly
            WFRBUXpPV1g3SVpoVVk5elZVMHd3Wk0KLS0tIHpMbE5tUGhSNDQxNE16OFF0MEt5
            RnJBaHB5K1pVOWNPTnhnQUZqMERoU2cKd1v8SnPsyPLRNQ+O11UUnIJG6BZ9gwB8
            uu70TIgnjo+ONl7cJz0jnqXdqISYqI+Pv0mn4jUX8WBkfamAELJKLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZWtiMm9ISVptTlZJN1gr
            aS9jZkYzVkdqbnlCTlR5TzNaUnI4UWhuclI0CkRvUWFmWUQ2ckRLZGNIbmg1S2xy
            Nm9wZ2JQUHBDQmNYUWtmNGl1N1FKUHMKLS0tIFR0N0Y3NDN1aC9iUWZHNWFKUjJJ
            TlJLMnJUNVF2YTJGQ005V3p5Zlhmem8K/2wkeA9cmkWuj2ERBa0ev+1m7Eet0pb9
            RGcUmKTbvDGPZHQNv6cpZPRQ/yjdShYzNU4ywJAl8/MNuGMRc7Knug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-04-23T19:32:27Z"
    mac: ENC[AES256_GCM,data:6OJoQByT7k4JqRGpums+wJmsSrOlF7BNx45dvG97cskiQaV/wNQsh3CF41qI+KT0J2h5X7gnxMBHhmlzTom4bHsEekPdGXJOYj/amnl4Djjtm6acDgv5m011uEpy/bAXa5oA3Vxmh30agjCaGjfZpJQvqRaBMQWnSN6hjPuoGYI=,iv:fzl8Zlz1X6/e0lkCtKWBrfnofG9vzCWVEiQDcRV9B9g=,tag:gbXWb2UeZAUMafgvC7fHlA==,type:str]
    version: 3.11.0
