apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
    namespace: cloudflare-ddns
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:jjRDyP8p5na1z4adZt8u8OMZlqPfx3yWQkBnAtIgFjH7o1Oe2uuKV12y6DZLMm/4sphpDnk=,iv:WC+IQcgYrJ83dW4zDOEqQXAXt9iGok/9rBA+Y6flVQA=,tag:z/X6EbcP6WKgmgQski+Dvw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUZrVFhzcm1ET1BlZUlZ
            ZEFNOWJUKzlKSlhsWDZJRXRsT0xZamh5bGxvCkR6ZzJvd01qdkNaVllaMlZINkNx
            OVVhWVZ3ZjVpZy84bHV0WDBwREpzZ3cKLS0tIEVFWXpUNTArOWhOcEpnNmpDZU9C
            Y2F1WXJiamhsTkRCM1FmRktkRE9OM3MK3UKNVktZ3KHlrpJ+SaFGE/kiPZ6ngehu
            +pgcGBhO+hfJ2jWSQkFRppfvqJNRZMhXdDxKKfa/PeKsy1WJshcPwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZEVDaGU1eitKc0lqQ3FM
            WENDVFFMSXFJRE1IeGhSU1ZWRVBONlpadmtNCjRQUGxPRGFueDEzbi9TQ3FmNnFQ
            SVJsQ2dDKzkzbWxpYVhkREIyUldPR2cKLS0tIE0zU214MmNKbFJJeDcrSWN3d2cy
            NmdYTHJGMGxCVHdVaUpCRXBNZWNqdWcKhQQe0avEJHwZQicxE1XhY5VjzqNPnKM7
            Vg/zzcHDw4SNa5tzMnym7dRDe3nCQoJaRC1yhPExRR0qMCNodtBnBw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T23:47:03Z"
    mac: ENC[AES256_GCM,data:WoFeLFHS6pfQC6kWoB35BPlIDSy2+kqfoCbFy/rPe3dwgbccTvcs20Pulv+MYlM3wEtKaZMKKBmpPapkjVoBj3+6FSapP+ONCGFw3p9HrE/1xLYkIbmieH2p3ec2H6B3JeAlMpxbHigYYqUq3lcfVXuJ6TeMAncBSH8tivRuHZQ=,iv:EyHy1T7yET+tkJ82kYz5Vgs1STZ+zAb39D2A9HLMSJY=,tag:QY52oLocZ+9ZvqEFFcp4ew==,type:str]
    version: 3.13.0
