apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
    namespace: route53-ddns
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:p30cXn3aNy5C8M7VwcFCOtcneuVrq/Pp/1XJEQpN3ZZ+Ozgxi9wbwHKuLa1U7aJfDkC0X0Q=,iv:t35ZcFbIkDZhLm5KpdmgbDwEWDtqkjfBFsn/ZEYspXQ=,tag:tzGxedCXGCk0r76VWOcSrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHOFlRNXcwU1E0YUt0RmY1
            eFlFZ2xlK0tKUU53L0pIWHM2a2JXVVVBSEJFCk1MSGtMYktLSll0cUFxQ3pBYlZx
            T0NON0RIK2lUaHpydUFCUEZlejlkZkEKLS0tIDVReW45dG9Nb0t1Y0phUmswZlJN
            VE50R2NSNjgrZkc3Q0gxbWp6aHVzak0KBSrBgwLtVtfcK9C+5+k/t4JVU/St7VIW
            EImGMnmQ0MMhQDWASrHfI3cKI1MUP8k+5I7e3BZU/tYvdI7Z9aKOrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-27T23:36:10Z"
    mac: ENC[AES256_GCM,data:cJZb76Vy33H+9XftSiHiFYt6EP8/R27K5L/oEd8ePmenorBJTSfOuBGAyi6B56ghnNjaAvv2GFdJPw2RQqo3ryYjz27WG5B0mtjxfdgu3Hhx26Nml9mjq0O77MkBlo8ntDaC6QlsuQiwFasADM0lZJHArkiWCvAaAxzMuvtnZBI=,iv:cLhd407mOo9K9r+NqdnzVICTAhHA4I63BF/sUZoBQ/M=,tag:FoywgXafJKdjUEBj3Q624A==,type:str]
    version: 3.13.0
