apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
    namespace: cloudflare-ddns
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:Xk5ih5PTPwtBhJl6Bk61+B1OZ2svSvmUxt75RXS7K45s+nG1GMocpwa/YUR/Hu5DtACugv4=,iv:TXqgzALRC4uu4kLH/YRybljncb4w4861vvmxRIrIXrM=,tag:H1aIQuKO64eHJaRM6XZ4hQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fszjt38d2jnw434z3gl6gv66ca79au03j6mgcr7f7f5w05cj85ts06m53g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOUZrVFhzcm1ET1BlZUlZ
            ZEFNOWJUKzlKSlhsWDZJRXRsT0xZamh5bGxvCkR6ZzJvd01qdkNaVllaMlZINkNx
            OVVhWVZ3ZjVpZy84bHV0WDBwREpzZ3cKLS0tIEVFWXpUNTArOWhOcEpnNmpDZU9C
            Y2F1WXJiamhsTkRCM1FmRktkRE9OM3MK3UKNVktZ3KHlrpJ+SaFGE/kiPZ6ngehu
            +pgcGBhO+hfJ2jWSQkFRppfvqJNRZMhXdDxKKfa/PeKsy1WJshcPwA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1phcmcgfeqr66t7kxdafckp860y67j6n6y2qrn76hk4fm2vd59pxsqr3466
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZEVDaGU1eitKc0lqQ3FM
            WENDVFFMSXFJRE1IeGhSU1ZWRVBONlpadmtNCjRQUGxPRGFueDEzbi9TQ3FmNnFQ
            SVJsQ2dDKzkzbWxpYVhkREIyUldPR2cKLS0tIE0zU214MmNKbFJJeDcrSWN3d2cy
            NmdYTHJGMGxCVHdVaUpCRXBNZWNqdWcKhQQe0avEJHwZQicxE1XhY5VjzqNPnKM7
            Vg/zzcHDw4SNa5tzMnym7dRDe3nCQoJaRC1yhPExRR0qMCNodtBnBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T21:02:24Z"
    mac: ENC[AES256_GCM,data:ECwduZWObpx32QD5lfYvJB12t+Qe4eST10YiwYKaDrGWFYe9iJSn7X2MChyhxoF7wX7ruFjaq12KhLgM4RbQKeUz0l1GeLDmdP34XWw8AZyKebdcQsxiOxONWDnNn1QQOxfO94z8xozR4TRoXP6VHtedySzJedyHlemJ4yUgAb0=,iv:tEZBbaH7fx2xFWH4DJuxhSzjpfqllhYJfIXvCINcyi8=,tag:rg4Ux1JGiFYoWqbwHYKVTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.13.0
